version: '3.3'
services:
  webimpetus-db:
    container_name: "webimpetus-db"
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'webimpetus-dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - webimpetus-db-vol:/var/lib/mysql
    networks: 
    - webimpetus-network

  adminer:
    container_name: "webimpetus-admin"
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - webimpetus-network

  webimpetus-php8-openresty:
      container_name: "webimpetus-dev"
      image: bwalia/webimpetus
      restart: always
      links:
          - "webimpetus-db"
      networks: 
      - webimpetus-network
      depends_on: 
      - webimpetus-db # This service depends on mysql. Start that first.
      volumes:
      - webimpetus-src-vol:/var/www/html
      ports:
        - '8083:80'
                        #      command: "/bin/sh -c "php -r copy('https://getcomposer.org/installer', 'composer-setup.php'); && php composer-setup.php --install-dir=/usr/local/bin --filename=composer && php -r unlink('composer-setup.php'); && cd /var/www/html && composer update"
      environment:
        CI_ENVIRONMENT: 'development'
        database.default.hostname: 'webimpetus-db:3306'
        database.default.username: 'user'
        database.default.database: 'webimpetus-dev'
        database.default.password: 'password'
        database.default.DBDriver: 'MySQLi'
        app.baseURL: 'http://localhost:8083'
        logger.threshold: 4
networks:
  webimpetus-network:
                        # Names our volume
volumes:
  webimpetus-db-vol:
  webimpetus-src-vol: