version: '3.3'
services:
  webimpetus-db:
    container_name: "webimpetus-db"
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myworkstation_dev'
      MYSQL_USER: 'wsl_dev'
      MYSQL_PASSWORD: 'CHANGE_ME'
      MYSQL_ROOT_PASSWORD: 'CHANGE_ME_DEFINITELY'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./myworkstation_test_db.sql:/docker-entrypoint-initdb.d/myworkstation_test_db.sql
    networks: 
    - webimpetus-network

  adminer:
    container_name: "webimpetus-admin"
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: webimpetus-db
    restart: always
    ports:
      - 8081:8082
    networks:
      - webimpetus-network

  webimpetus-php8-openresty:
      container_name: "webimpetus-dev"
      build:
        context: .
      restart: always
      links:
          - "webimpetus-db"
      volumes:
      - ./ci4:/var/www/html
      - .env:/var/www/html/.env
      networks: 
      - webimpetus-network
      depends_on: 
      - webimpetus-db # This service depends on mysql. Start that first.
      ports:
        - "8080:80"
      environment:
        CI_ENVIRONMENT: 'development'
        app.baseURL: 'http://localhost:8080/'

networks:
  webimpetus-network:
                        # Names our volume
volumes:
  webimpetus-db-vol:
  webimpetus-src-vol: