version: '3.3'
services:
  webimpetus-db:
    container_name: "webimpetus-db"
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myworkstation_dev'
      MYSQL_USER: 'wsl_dev'
      MYSQL_PASSWORD: 'CHANGE_ME'
      MYSQL_ROOT_PASSWORD: 'CHANGE_ME_DEFINITELY'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./myworkstation_test_db.sql:/docker-entrypoint-initdb.d/myworkstation_test_db.sql
    networks: 
    - webimpetus-network

  adminer:
    container_name: "webimpetus-admin"
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: webimpetus-db
    restart: always
    ports:
      - 8082:8080
    networks:
      - webimpetus-network

  webimpetus-php8-openresty:
      container_name: "webimpetus-dev"
      build:
        context: .
      restart: always
      links:
          - "webimpetus-db"
      volumes:
      - ./ci4:/var/www/html
      - .env:/var/www/html/.env
      networks: 
      - webimpetus-network
      depends_on: 
      - webimpetus-db # This service depends on mysql. Start that first.
      ports:
        - "8080:80"
      environment:
        CI_ENVIRONMENT: 'development'
        app.baseURL: 'http://localhost:8080/'

  # e2e:
  #   image: cypress
  #   # build: ./e2e
  #   container_name: webimpetus-cypress
  #   # depends_on:
  #   #  - webimpetus-php8-openresty
  #   # note: inside e2e container, the network allows accessing
  #   # "webapp" host under name "webapp"
  #   # so "curl http://webapp" would return whatever the webserver
  #   # in the "webapp" container is cooking
  #   # see https://docs.docker.com/compose/networking/
  #   environment:
  #     - CYPRESS_baseUrl=http://webimpetus-php8-openresty:80
  #   command: ls -la
  #   # npx cypress run
  #   # mount the host directory e2e/cypress and the file e2e/cypress.config.js as
  #   # volumes within the container
  #   # this means that:
  #   #  1. anything that Cypress writes to these folders (e.g., screenshots,
  #   #     videos) appears also on the Docker host's filesystem
  #   #  2. any change that the developer applies to Cypress files on the host
  #   #     machine immediately takes effect within the e2e container (no docker
  #   #     rebuild required).
  #   networks:
  #     - webimpetus-network
  #   volumes:
  #     - ./cypress:/app/cypress
  #     - ./cypress/e2e/cypress.config.js:/app/cypress.config.js


networks:
  webimpetus-network:
                        # Names our volume
volumes:
  webimpetus-db-vol:
  webimpetus-src-vol: