version: '3.3'

services:
  #1 - Run the mariadb database
  workerra-ci-db:
    container_name: "workerra-ci-db"
    image: mariadb:11.2.2
    restart: always
    environment:
      MYSQL_DATABASE: 'myworkstation_dev'
      MYSQL_USER: 'wsl_dev'
      MYSQL_PASSWORD: 'CHANGE_ME'
      MYSQL_ROOT_PASSWORD: 'CHANGE_ME_DEFINITELY'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - workerra-ci-db-vol:/var/lib/mysql
      # - ./wi-dev.sql:/docker-entrypoint-initdb.d/myworkstation_dev_db.sql
    networks: 
    - workerra-ci-network

  #2 - Run the mariadb database adminer access
  adminer:
    container_name: "workerra-ci-admin"
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: workerra-ci-db
    restart: always
    ports:
      - 5502:8080
    networks:
      - workerra-ci-network

  #3 - Run the workerra-ci app
  workerra-ci:
      container_name: "workerra-ci-dev"
      build:
        context: .
      restart: always
      links:
          - "workerra-ci-db"
      volumes:
      - ./ci4:/var/www/html
      - ./devops:/var/www/html/devops
      - .env:/var/www/html/.env
      networks:
        workerra-ci-network:
          ipv4_address: 172.178.0.8

      depends_on: 
      - workerra-ci-db # This service depends on mysql. Start that first.
      ports:
        - "5500:80"
      environment:
        CI_ENVIRONMENT: 'development'
        app.baseURL: 'http://localhost:5500/'

  modern-api:
    container_name: "modern-api"
    build:
      context: ./modern-api
    restart: always
    depends_on:
      - workerra-ci-db
    environment:
      DATABASE_URL: ${MODERN_API_DATABASE_URL:-sqlite:///./modern_api.db}
    volumes:
      - ./modern-api/app:/app/app
      - ./modern-api/migrations:/app/migrations
      - ./modern-api/seeds:/app/seeds
      - ./modern-api/.env:/app/.env:ro
    ports:
      - "8989:8000"
    networks:
      - workerra-ci-network

# Add Keycloak service
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KC_HOSTNAME: 0.0.0.0
      # KEYCLOAK_IMPORT: /opt/keycloak/import/realm-config.json
    ports:
      - "3010:8080"
    depends_on:
      - workerra-ci-db
    volumes:
      - ./devops/keycloak_data:/opt/keycloak/data
    networks:
      workerra-ci-network:
          ipv4_address: 172.178.0.11
  #4 - MinIO Object Storage (S3-compatible)
  # Note: Using external MinIO instance at 172.178.0.1:9000
  # Uncomment if you want a dedicated MinIO instance for this stack
  # minio:
  #   container_name: "workerra-ci-minio"
  #   image: minio/minio:latest
  #   restart: always
  #   command: server /data --console-address ":9001"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin123
  #   ports:
  #     - "9002:9000"  # MinIO API (using 9002 to avoid conflict)
  #     - "9003:9001"  # MinIO Console (using 9003 to avoid conflict)
  #   volumes:
  #     - ./minio-data:/data
  #   networks:
  #     workerra-ci-network:
  #       ipv4_address: 172.178.0.12
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

  #5 - MinIO Client (for creating buckets on startup)
  # Note: Disabled since using external MinIO
  # minio-init:
  #   container_name: "workerra-ci-minio-init"
  #   image: minio/mc:latest
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 5;
  #     mc alias set myminio http://minio:9000 minioadmin minioadmin123;
  #     mc mb myminio/workerra-ci --ignore-existing;
  #     mc anonymous set download myminio/workerra-ci;
  #     echo 'MinIO bucket workerra-ci created successfully';
  #     "
  #   networks:
  #     - workerra-ci-network

  #6 - Nginx Reverse Proxy (Unified Gateway)
  nginx:
    container_name: "workerra-ci-nginx"
    image: nginx:alpine
    restart: always
    ports:
      - "8888:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - workerra-ci
      - adminer
      - keycloak
    networks:
      workerra-ci-network:
        ipv4_address: 172.178.0.10

  #7 - Run the cypress e2e smoke tests
  # e2e:
  #   # image: cypress/included:12.8.1
  #   build:
  #     context: .
  #     dockerfile: ./cypress/Dockerfile-cypress
  #   container_name: workerra-ci-cypress
  #   depends_on:
  #    - workerra-ci
  #   links:
  #       - "workerra-ci"
  #   # note: inside e2e container, the network allows accessing
  #   # "webapp" host under name "webapp"
  #   # so "curl http://webapp" would return whatever the webserver
  #   # in the "webapp" container is cooking
  #   # see https://docs.docker.com/compose/networking/
  #   environment:
  #     - CYPRESS_baseUrl=http://workerra-ci:80
  #   command: pwd && ls -la && npm install && npx cypress run && sleep 60
  #   # npx cypress run
  #   # mount the host directory e2e/cypress and the file e2e/cypress.config.js as
  #   # volumes within the container
  #   # this means that:
  #   #  1. anything that Cypress writes to these folders (e.g., screenshots,
  #   #     videos) appears also on the Docker host's filesystem
  #   #  2. any change that the developer applies to Cypress files on the host
  #   #     machine immediately takes effect within the e2e container (no docker
  #   #     rebuild required).
  #   networks:
  #     - workerra-ci-network
  #   volumes:
  #     - ./cypress:/cypress


networks:
  workerra-ci-network:
    ipam:
      config:
        - subnet: 172.178.0.0/16
                        # Names our volume
volumes:
  workerra-ci-db-vol:
  workerra-ci-vol: