# Dockerfile - alpine
ARG DR_IMAGE_BASE=alpine
ARG DR_IMAGE_TAG=3.18.4

FROM ${DR_IMAGE_BASE}:${DR_IMAGE_TAG}

LABEL maintainer="Balinder Walia <bwalia@workstation.co.uk>"

RUN apk update && apk upgrade \
    bash jq wget && \
    apk add mysql-client curl && \
    wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc \
    --tries=3 --timeout=30 && \
    chmod +x /usr/local/bin/mc
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

RUN mv ./kubectl /usr/bin/kubectl && \
    chmod 777 /usr/bin/kubectl 

RUN kubectl version --client

WORKDIR /app

COPY ./backup_database.sh /app/backup_database.sh
RUN chmod +x /app/backup_database.sh

ENV TARGET_ENV=""
ENV KUBE_CONFIG=""

ENV MINIO_HOST=""
ENV MINIO_ACCESS_KEY=""
ENV MINIO_SECRET_KEY=""
ENV MINIO_BUCKET=""

#ENTRYPOINT ["/app/backup_database.sh" ]
CMD ["sh", "/app/backup_database.sh"]