version: '3.9'
services:
  #database
  mariadb-docker:
    
    image: mariadb:latest
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: workerra-ci
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    networks:
      - workerra-ci-network

  adminer:
      image: adminer
      restart: always
      ports:
        - 8086:8080
      networks:
        - workerra-ci-network

  workerra-ci-openresty-php7:
    depends_on:
      - mariadb-docker
    image: localuser/workerra-ci-ci4:latest
    ports:
      - '8084:80'
    restart: always
   # volumes:
      # - type: bind
      #   source: ./workerra-ci.co.uk
      #   target: /var/www/html/workerra-ci.co.uk
      # - type: bind
      #   source: ./workerra-ci-microsites-php-mysql
      #   target: /var/www/html/workerra-ci-microsites-php-mysql
      # - type: bind
      #   source: ./devops/nginx-servers-conf
      #   target: /opt/nginx/conf/nginx-tenants.d
    environment:
      MYSQL_DB_HOST: mariadb-docker:3307
      MYSQL_DB_USER: dbuser
      MYSQL_DB_PASSWORD: password
      MYSQL_DB_NAME: workerra-ci
    networks: 
      - workerra-ci-network
networks:
  workerra-ci-network:




