apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: webimpetus-mariadb-ha
  namespace: test
spec:
  # HA configuration with 3 replicas for Galera cluster
  replicas: 3

  # Galera configuration for multi-master replication
  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    replicaThreads: 1
    recovery:
      enabled: true
      minClusterSize: 50%
      clusterMonitorInterval: 10s
      clusterHealthyTimeout: 30s
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 5m
      podSyncTimeout: 5m
    initJob:
      metadata:
        labels:
          sidecar.istio.io/inject: "false"

  # Storage configuration
  storage:
    size: 10Gi
    storageClassName: "local-path"
    resizeInUseVolumes: true
    waitForVolumeResize: true

  # MariaDB configuration
  rootPasswordSecretKeyRef:
    name: mariadb-root-password
    key: password
    generate: true

  database: testCi4
  username: webimpetus
  passwordSecretKeyRef:
    name: mariadb-user-password
    key: password
    generate: true

  # Connection settings
  port: 3306

  # High availability settings
  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: mariadb-primary-conn
    secretTemplate:
      key: dsn
  secondaryService:
    type: ClusterIP
  secondaryConnection:
    secretName: mariadb-secondary-conn
    secretTemplate:
      key: dsn

  # Resource requests and limits
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  # Pod disruption budget for HA
  podDisruptionBudget:
    maxUnavailable: 1

  # Update strategy
  updateStrategy:
    type: RollingUpdate

  # MariaDB configuration
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  # Metrics for monitoring
  metrics:
    enabled: true
    exporter:
      image: prom/mysqld-exporter:v0.15.1
      port: 9104

  # Liveness and readiness probes
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
