apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: webimpetus-maxscale
  namespace: test
spec:
  # Reference to the MariaDB cluster
  mariaDbRef:
    name: webimpetus-mariadb-ha

  # Number of MaxScale replicas for HA
  replicas: 2

  # Services configuration
  services:
    - name: rw-router
      router: readwritesplit
      params:
        transaction_replay: "true"
        transaction_replay_max_size: 10Mi
        master_reconnection: "true"
        master_failure_mode: fail_on_write
      listener:
        port: 3306
        protocol: MariaDBProtocol
        params:
          connection_metadata: "tx_isolation=auto"

    - name: ro-router
      router: readconnroute
      params:
        router_options: "master"
      listener:
        port: 3307
        protocol: MariaDBProtocol

  # Monitor configuration
  monitor:
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      auto_failover: "true"
      auto_rejoin: "true"
      switchover_on_low_disk_space: "true"

  # Admin interface
  admin:
    port: 8989
    guiEnabled: true

  # Configuration
  config:
    sync:
      database: mysql
      interval: 5s
      timeout: 10s

  # Authentication - simplified
  auth:
    generate: true

  # Connection settings
  connection:
    secretName: maxscale-conn
    secretTemplate:
      key: dsn
    port: 3306

  # Resource limits
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # Pod disruption budget
  podDisruptionBudget:
    maxUnavailable: 1

  # Update strategy
  updateStrategy:
    type: RollingUpdate

  # Metrics
  metrics:
    enabled: true

  # Service configuration
  kubernetesService:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/allow-shared-ip: "webimpetus-maxscale"
