service_name: wsl

targetCluster: k3s1
targetEnv: test
targetNS: test

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: development

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: helmfilesecretsplaceholder

serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31179

# mysql / mariadb
db:
    hostname: AgBWEhpQlg9jV4J4JyhGDWip2FRciqZXkjl0qCNm7DRKTkh/8ZFm/wa8h5r70Y78f9jyAG427T++LHsl590WMjE+w2W4rironNbfc44zf1mthSWdlR1lDhvmPXcF9N1kauzD8CJgvtJLHA5LOdib5QR1rUUlYgB46RlvcHLwXKulyFif8FpHKxY77lLIxlV2O6O8IAxOxO+wVULQxrOraFNn/anphoNUOqNqJrJBLePJX6m6ji23FqevdQ2l29PLtzthUcG/Z1ku8KPghNR9UaVM1zPIbDhTF2XWuh5nusH06cIN7gaq2PoOMo5Z2O9wxxzFdQke6l2tYLVxcaK3lUHAFzZ/KrjVZiRb2NyCW8I2CqOqFZlD2fgxgDTGu1uO8dsh1sQpGOdhT7rBo4MEDTSlIKyXFs+weBSdnUmTi5aJmwiAOObzQGgfMrqoPCmCbt5y8pvOECIG6iqOZ2q2zVSlUFJAdz2sJwRmf13Sr2to927lThwwlO/O4kMK9/Gm2QijkfAwReZxcg/ennyFvaeyNLebRyxrRYpJkVyZejeK4GP2Y/FcjM6Dop1dNDbM/c7pN+6+kra4t4E0QEgdZcIKu8CrQnG4dfTLOYo7IFKd+9ld6x6mFxRJirEtnqWznf6vPS01gGITkC8KnN0+qA6O4TBoidR38CIdYWCzYbwrGwZ+s4Vd0VRWn6PRcq5U2l9xNSZhWcIf4Nk+RzY49iVpbpF66+2L
    password: AgBiuq6UppWyWRrcofKHNqRLTYYWl8mq0IAXfGTgOid5705TJBs7BTH/2qccgCa+5SB+sdKTh3KgSWen2pcdI5g/E8E0auPfGEuXfqEZUzVAJLyyTb1HXqdvvPeWOeGysroyRmxb6K1hDd8Zr3ip02MTgJdUOK/Xb1H7s3QN2YI3nmrQkSG4qgKqVPSAMuofYJOdEOw7KnJbrRLeP5294lMhakJ30YDVqijDbg3FmlpZaGU2sQ5xNkeU+ePxL9AfPTl4a48Om3SeissWSo+bjY1fonwrM2hyaNC3zZujBH7t+bktQTFCpYyr9OAATbQoa5RXNwrnspffBug9qJonRuD6pVyjt8rEzmBAcrX/WaOP/Bx8YWGQfNxxTtklhqM15bMM4H8ctEno2jFAPaXGBwfLYq3n7xxWu/pIHxthMeD0hJfF5F6alYwOJPPo3DfTYz7BIChm1gRMrusImYPrxa/cP0lohHp9HAYDPgr5CE8l/Qui7TX2CbwPFWavTI04svTurSyumR3X/MxyYg/kWeq4Lni8V1pi5e13+5dHscSJXA8VZbK03BfsCLGJfMuUmv0Udl1i+WqboH/n5x0UjtNotYaiOV1LvbGuJNBQ0XfTaRJ6uVMtQwS0M8lGxvonJCajDivE2kuKHGtYMXER6GnFq9pJWIaSNLjq7mY9uhi0atBJKPI53iuxWy5A5DnAROJlOsixfKMhmoDoLA==
    port: AgBfYhxqBpHIApLyTlUDTYpqfNbBWQSUzpfpaizuXvghRUmrS0F9Y0DDBZ9WYP2fn8uOaOU/VUh9HXL6/sf69znMoVuq2pe733zG4MCH3J5QhLTdC6gYqmz+Ciw19WmCU4K2ae8PVfsaguOwQ8vTB5M80seVPhnDQODGzEVAzmNIM/b7Odo1wACjj6XU6gVCgXZqcf/GCk702kWpAnk2eR3sA/jxFEit5Jn94EyT4MRPl7y0dCwa99tX9bs1TNdThtMG4gzjAlTkbUO/nQSop3rkBsAaU2plNfF65/ho5ofAdWEpQnu6ZNLy3PcCrXqQwm4N7KkOyI7V71ZlrvgFpGJ69bJRgOuwNuAShTiGP+W/9x7ubn/8s7tMt3nUMKiIkw46QIVbalqC68GdDkNf7TQRt7dfbF7eqIbx2FB6WNyZ+qMCL2CQGqpOmV56wJOkzY9prZm1hZTWmu3JBCVBSytoiFm7W957yETTKTk2QplHp1RPiKF3W0M2jRAw5Eliuya5H+Scl1PWbK1CNS59BF5ab6sVCre0yHgv+uGcMHv/dZ1p40o3I4wqPOSe7uwAMRte2o5shUSyMSPfJc1rNiyYl3grdNWlcrAl1WkZBh0B674JELKz3ljRIwxiwUwgN2X/pP7I+Mv0/XJ7+D8pCscqjbCrGw0ejGladH2ET7pbGYfmTLq2Se6vK66S2RcooUJzsnj4zg==
    rootPassword: AgCZnpM4ZVCLUj4E8ChKk+BSF33w3fRQ9+6IWeemdtk7hMbJVy34PSN/dVSlynjWCMJhIofzxlcdka0oZVhQhUUQkavZTgf7ixc2+96xY1e9k6tCoJneS+5j1TR1oGa1QlrrUzKsQ5fhEtxfBWDpkDKkfLYeEA6eJGOp/qApsvjwf3t0qZErWmEEInVCZV+QCQucnOgplLW33uVAtw0l+zImb7AU43B/GlzqeUZsBDrU2J0IunKeMCfoLw1MM15oTkjyyk/G10C2kTPNQ9phXrwvbdjMsZvr/xGQOylWF6mJyZRHfXe1KSYjtn8iAFzLZZQbCkWyuBgoELU4921di8kSRAh7CZDH/XcjCXGam1mNW1dgYdWUvD6N7UTqFFVvS+Fnlhm+2y9dIGWouY2ADsMrGcQWnLWmZSS3oOZ9Hfud1hbpZBKQ3WQh/mia1Qi+0P8XMFpJczTRAUp8opq22tIQHCE2bnvoviyhTAHBzpSw+bCJAZTWShpeEBueBRCABe2mBq672ifl9e6dQ3vw4EHyYLZcB/a1r8Mj7JZq0K6yO7d/NbQW4vjO4XFX/qN6OQFgMo9DVEdmmM1nX1N+WTu4hh62iKr02li7tgmXX0M0B4frEi0Cq/ze7yuyL0zVD/TiGvMvIU1gr8XBH9B4bmQ/ikBvJWTEn+14S7ZIeSITLQxNLa32og02Dgz8DlKD/3gYB9pgHqAEM8WsJg==
    username: AgA5KOCJbtSzLCBcqi0UVfQyWe8LBEUz9Au0hEcp8JKgpptklg4FJy9df2AuH3zrvP2cNZBXjDKRpZexhA7Sxi52RXc2KQvmb3H41DRTtKOi5MmkVl0vWPLpvaKneXznMsF1UqfbVSSeORhnL7hw3Y/57cGrvAH9jid/3kK3jp3+nUZwzPbVawPRd76JxHRMO6vYaeTxlCEmsqOF15seIq3KJLOlCYFhqI8lkcC6L04UJ9YIXD2DUP8ywx22Ajxh3LycWKQQidl8x2ADPjy3i5a1dKsLH/3Kc87RL//80fP8/5v6/aziu1TZYAmdhUkuMVoMvQQMwxuyCLzvbRGry8UXEtYhWe1eczjk34C3RGouB+Sxd10peQIldlsI8yVRiYfcEtMbs8bgBccn0y8OadblNkVaVolpqz33gGnf9q1cdu6cYVWhEtxPlhGTR/o+mvB7uEH8/NBMIHaK/EJwAs69Lx2VAvC9NNQUXpDqx7xZg5lJIv+vlnLtmWceJ6UsWf5f4FKNqsTL4XKNYOznWYqbZoqe22VP9udlWJvIxOt7DfRn5kJjAnRG4u1nqJOn67AETWfJ/awuoQhtKHKEebcnlbwvjFe1YZbr7eoLEmyBGePJklkYO3+VZQwUgLKTF9sAnSzhNP6oSp91fvOOPGwHpF2BUWSfjaeZ3RnSmfbsnqyYq8i8Qa2+Tn2k0wDGP/p5IdGD

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test-my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

adminer:
  port: 30880
  
resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80