service_name: wsl

targetCluster: k3s1
targetEnv: prod
targetNS: prod

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: production

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: AgCoE4JDvOPkFoMAZHPjqYhPvU/IcjF6ZDwSgneorLMYh+y1Mq9AehO44JWugNuRK9mYgPCsazpzHTiwNryesZeb3t8mIgK2ZqPRFMW1A6Rn4KEq9HIxD5kaKQrRpp4qkzjFeVc10Iw4b/5o24v/QUcP5wCyXS1oYqWN+HauyV56Q9vNSemBSkIwwKvOWDuDpPSVKHEhoHEAa19ioM64hbZ4QPBi9f9jmOTXHuOjIEydZQkmcODZLJdFwr2pDlg2nud8uBJpwvXOjga57rXF4jytm3GKJ/z6XcFMwkrXwRDsUqvqLT3p6t0i59z5i3qKwLLgXoE0F4YSlETmEnWH8ESV85P0NF35AS44TdfSU8hFbS2zek1Sqx5TLaQX49FjjUQWInzjI+2dO5YmXIHeiFVb+os2aDeTRt8iRyxVeTpQ1ngSPLiGnzFB3XrhaWM3t4QbMkmffk9wrbxs23T8Ys8evh/WXqqFUH04rkSGabaeGSV8waZhcf5OocsKOfxAgsZTcWqPZ6Wdv9nVsY4THIq5rT2t7azpQRlWo47BN/tI9k4K9wDxOE+4Vy96VdqJ6RThA79S4rlDk+A4oeIYfSH6jKX0LQ/Fztul9guHAricyLutTh8gdIyNZyndNuIdwXMivwkOAIFkttqCsF1ZHTl0lZVdj/vASsnIBLq0IMExBQUGVyhjgLDC0ugLgVgFBTv30Ai360CPgfI1f+awAGoBmqyGR6eARys8UBmOCwYz9bHDJbDANLbwEu/CG2rdz4pPzBH+uNKcR1fyOcNaz4utvvgHAXfEYN8e2R4I3rFXIeipijO2o3TN1hNtZmGyzErK5lgaKaDpLbnltx7F/yYUBsDtqCBXvvkz5kkuevsIbBnwQpt7o50mAEa7SYsv+mMQHzn0IXfABimE9OAtq56dh0+edKEYLZVCyujRzzXT4vrKA4m3GEfp5J8yEvXjR0CAzb0+1BCf0VJqzwY8nK1wwmGnZymr0kMMmoJ+BaJi4xeMngT/2SbQSaSDjc8Z9FSoLjWkBKbenaeUy9JvwzLGW0jimfRXBWKr88UzL/QoJ6UpHmMEb3baJ7J3p0zSP3zinIVhkxDuEoW2waM0Y6OY6dgMPxgW3666/A4r1h90N0C9nSRTW/nCIpo9dqGKvYzTM5H8USPHK5Uv+RlZshOdJA5laTdu7Lk6iPyGp6aPqTAt0SF1OijBTXWhH7LMtoPAFnp6x1zlXClJ5LDzF86VAVnQCKngxOAiHEMphFWeSKrF37FkcRW5kBTKI61N3zShK2203pQSZDPSnhBIx6ukwWCeXIiqcZs3QI2z/3yQtPPaxo+sw3Q7prQJ3tUrdJoYP/JkysIUR2EWYknOgmz0k++fQnpEzaXfBoG8bu+mBDaHmDwBDX/tqZ0RIek2FwxT6Jl+km05BoSrAArHHAqQ9HwgA2J1SZmG0pZrffisQM7SQ16PX1yYsC89IM21144Fzl7fmqmoFfWswMjXR+cBxHBfByNpZwjiA/x9SCYFJWRYSpdRASz1WJb9pYegwd7WbdgLHY/MlPM5Sgl/tou+C3D935cCXNUqWqX17IhR9to7rQQPAmQjj6b0wpKGeJnQ4u5Oyqu/JcdmfMYqtfHNhplWulmZZ3erPkyLN2DVZmh8Gaeogpe0FayAPmU1bkQ+BUQFUwdxowpidCUD2PP8tZL/Rn2ILqYqaynb0CViFOog3vfZzTTVVLQI9ZWgcIp9Db4NSsVIzTkP3SRWDLOBIkFEIMVJhBs9zCmrtG2Nu79pCqMZ/TQbfWs9rveg/l6pPwyzIkvS8ouXgsLpR4JlNcgRK8I/Z+USXLhGCj3cnUJhg7rhHUNyE6SCi9TO2nqmoHVldNKG+LNUeplQZBxdoppG/I1G0e9msf6iUqr2hYkPpyKiqCZnbvxDyM/a2LayRML8cmymR2QjMvlinkaIWLijHMHsEA0glIzZoymMu5Eii45/DrD+pKgvV4Jg7kQHvwKf3d7xoGyd0a681rtZmJ0g6wxUkoofqVMSd5OsrNfLpN1DzfE2W52sCtKCyFcOzNHQwRJijymxIAfyEB+cny8cieF9EsGbWLGGk9cTdf2ChSh8Wg531emYQ8oxQkft5eBB8h6gy1ZZFOTIKhjrUdkJXW4bssiCdhftQkpihkdvRjo3L1ywOPblS+Agj+QWBfId/RKJj+PVkDfdNouF7gVsEX9FyLp/CEj7eugUpSW5F5850PJBFHlh84EQib9Ktc/yi3q+g9j3xx2QMzou7i4XfyQ1x0t8GgScLykopFNwiOSj8Wb0jw1mOpSNLQlwfEMDQ+JoCIX1/9FREXsQceLoXavJM15GJ6yIaimt4YT5byGe5Rn/YJzZcxIA2Q93xrIF2VgSDWWuxyRUtv5K3kMmnZ3AHGYGDMFTnQJQlGnBHmykk+KDA8X4Jcft093r9aDNL74ujI94ipTSQGflR+zaW6j6HH7+ztTcOHjMw34NeXvODWAGQ+rZkp1VP+Ye0HM8zN+QMRF8jRfTGR+dNis0WpbwPRXrgYG9JTeanK9iLCSFD3GwbKjPc5rv/V7S4fsDwr+3SsvzDuVnTmIXPqJ7dAITXd0TSpj0iqagLrLbJp2NJFT18Szaf+xqFTnVX5oIhri2vnw5gMyBfPrU4lV954bOINCtg+WAWUSs9TnpNChFlPEB0fPEzz91Y90h3tQf98ED0rXNwRFxLT+qqUpWaMT6jplD38OJK6rOPsr3EU/dkFkKykEpa5Rx1KK5CZ4ruKXrOkkwy6unrRObDgu5vVwvne38bP/MqCF+g6oqXq7cjcsiQq8cvRa1W7imwtGofH81Z4X7IP6pNjpWQokdPUh2UhIHv6cX69RjGCA3+/Ik6N5QbIPDlS36pAuVGFmr/FfyNgkyNxDwRPdoim/VAvp2JvranT9n8cg1aBC/tcVI+Ne/Hb9XWzkptpnSpBSchfdAOJnVjddPV4v2Ncw2fcWee17d5eS+RaO2YALC8cMZIoBPrwU98w6f9MhblgE2mG7BwVh0LmDPpGfD9ajvarp8iVOSxGc6hz+DU/Uy1AD6ExD/P7p/ZVAqkrWXzmZGyPIgMBGnkMruaNB/0xEC8/6A8XfwokINl+18t7gX9U6jbR5bPh1Hs9cyV+UQjvcGAhh9SzuXISzewyfMfmi6hpyMCp+Pyw8J9eGn5v3BURVpG4RrnMVVUQfzlDnJ3hDZftAdFQGr5zzXJ8UwMCIX4OersW3C7zSh77D39GSKwAbbeN0ViWIkwzzFiF0Ra3ShH8UdOzBad2ojVmo7k6dYZeCmkcJYTl88JAEzMp5Ox3En8jV9QnVI9lhoF7EPm6jotqIKIThBaiBrAtmVnQbOWTlQHNEPyxfTyia8C7e537hCwwpgbxqiNg0dMzIiIc06i+Qhewvzva9/RUN7gShNbl6ojBBhMJ/Juw9UgZ+Fc/WF6JbHUvYRvw1366XDcRcLfJoOTnHHW/nMye63+wOpleEtDloAL9nu5Vya3Xo07up+nGEAkHzaIEvBpuWPFF4xzss4+vpJwmMN3HKQNTdc+zGSKIXe/6wTUNOuDmFYajbx1nGG3iciAt94vGj0sFKT8FLUmykwqd3c9Ly94R/qg6OTRxeaxIAXaBZfOqysJvOLVxblNCYU2dszIhjsw/DAZEdOnWV51knURyUXBA5qint3hIZPKpUx0nSFDMKNSne5AUIRiqai98PfDV1j3yIGp/EHBbbH9Y88CpwsW9/ih/5LmXo0S4q3Yzioq4bvr14idI2T+0yKtqDxMi93NyAG+inkqrZxYMfRywVZcmaA5RBPqxITbhZ4AyusmS/KMXjnh06ZBufS8e8eVvaFe0dsdkmyOo0GKjwuuS+OhBnwz7i1+5Q+IjG9gzfh6o+1q2GQmm7TnP9awg+OM9QGPIgdljIfycFHzyZUQwhu7kZDZaSzMkF9+ZKGWe1Nds5k+wxQ74zktUiue1roLMVje3BHbgcKJGz8rBbb/JYjMidLci2Y227EpPRHrJX70ZJhL6ubqnTjNh9u9nhd6IMAIzAWEPpWYEYk08BJ/Fl+ocxbbGdj5rUoTv9zG+bi+dktQ7tFfSlnhxusKLAn6or6WrqjDWJDroyP3tTcekbjrQKYnJmFxbsEkvBIicrH0jiSkDpym6impvS0V6mscaFOeNnUskM2q7bG6UXREG3X9D6ahMFqVl6sowQpXaYVJbx8Aecj9X0jiESXmaZaiujWG9rRc4V1k+WjMcDvrS8T7uw5qJwuzDjP06kInaalwEGuhxFjgCXqXrxpNrJnML0Q5BK3nQPaqLbeDOKqrfXG+HmrPEwKHVTSi6fF9Mq2aSZMb/XDJbbyRq0rk/omtFftffBtEPQqTlIVzei1qaHHrssxp6cXpjPbL8jdI+Qc627Ji/ZzLZdCVmo5umKFe3AflDEQdXgbbfOHVoVYVaz/CIBwj6DiyvpMr03DCyJHYBt6TKfFepzsKyTtkG5itYLFeGfNxeBCpL+icJ6SbjgQQAIuFH/4P7NMlSnrMndXEzTJshaSWVgwbEuAh6xoxFWAoR6xg6cj54enZaW/pkzu+TXgAmMo65Hn4iwfS2up8AKiP+AA5DLMhNjbrjfCdfnIpipbkJjb+USw/3ENAz7LzqualVl+astSsIRkGfuHBkwtw0MTdoi64dqamlYRRHfMR5YbpJ5I+/8SQ1VI8uwe6zjY60vxAnmKoXE5JKEMZfnWXCFlmOxL6aefLPJ0vJz0sev3DqaDY1DlPIEcIrYaZfapTthtmfdJnkNLk/DQ0NUZ5ktMUw4NekwGAfmWc6MoYk5xcRRhzP7BPPe1qCUbj4WsUPJxDSwlBMDFyPLmVlJcKlPUGDd3evBPE/JP+QGbqrATHvTASzUX3mathrZsuGehWZU9jsznfe8UHD/QEfAOOHaF4ZHmdf9pNLSxs8U2o4R0jRCL154dHfIMN/ewdPGjkR3oPYR00Zclpgmd/s2N+24MN6Vfn81DBwbL2wyswkolVcn5O6qi5IONt6QKcGLVRADMXZwvRfbZaFLNXC9YskAhPb5LX4IxOfHjHnahWa9bp8FDsM35RaurX95WvvP3AT/xednA8ehD+7/zwcdXslKhPARqVNsV2/7iNALxUPrV7ldIM3DezE9LPnmGueNcPbFDkgwZZXi2cYcsg1ihMMvtGHYHX9SFVJ6+0oKDlFMQrTK/Ywail7KGaT8vYPltBnaRndF8U1UMX176dSNJj+uI5XYAs+mwu/SPw9q3efPhKxt1VwKt64xiou59XquVG7n0z3JitRtG1evHyrUBeKZVFkEbM68sJ+evdmJXPMXqx6hqwpmUa/jK17l8j3G/o3crtbCkjvNv7fMgJGduQwTpVDug3VJInKlfyVuQmdcMY2lpHacb+PqdJ0P97sZb0cSnD0PsSc7Us5aZDjmBM7Vcw7Pjgt1jT3El8YZzI/mjCnXahIB/X3psU5xEIQLsCb+OtRWelHaBd9LJAZBeDyVWxS0XDdT2Le+dHAI593yNRknrz/CNugFF1iX08d+pJ+UFogQ+nYGXgoUhkEJdqSZEub1boFtneoIyPsyZNIrqlrMezLkDxZYOGvcvMEOJ3leLm7KgtPrviBDslPbi4I4Ruq8/ag4Udi7LedMPzV8bNuDPsQ333rxYCEuxmozOgS58mgDYmsOxBu/48S1H+VciPdNGXb02IIbA+g9cs3PuJM6dnsBHXbcchiJqTF35XZlQqRI+RX5idXFPV3kA1VnSDlpdZY+5EDbYT/AQ87SIvRlXgIYlxmyN4KCiDOdDXfzYAv3E7Z6emgUFFuJ26c35MGkgn4zVMnv2zWtnT4sTj/zKNiLLdQwq/0y4kg1Leddh6i7y7v8ALBNJ0WLXZPrANDQLgPxXjIX/v3FQr7l6bF+2B5UD4pp9r4XZU5LQhaPh9nonFqkJoD7ellQcy3zSyjUd3iJxzmBuuZ1ar285soFS7mRKP2WLeFsx0c6dcP9BYN6nTHlt5fFJmTE5qfLF5TLY9Ky0Mi4j+f4bxUTfle214qAM7AHzHF/Flwb5q2dpESYAV/RH8XKgOByYl+aICzywGkfRziDQ4Y90JmlpkxC5SlZN+VIZSoB3suRMqt2DCusYNon58NXFt5pgV5b+8UJm/GNYEbDBV0anq1mv9lF6ZQwucb5zZ+q7ViloGORUPMbxyJyusCsueB3pOCRjvqXTR9GtA1G2VrWw/PtsKRw8YWOcoAduNInrfGSXHPA9biPqQv7xTicC90u+pr1x0mMQJlZ4nvZ+RgOyqkF4CCOiwqkfDZAAv5OfL7JMrSz43TjGlDBPa4jaqNr3EQ9ilY2FSCCMKBXLAp5Hw0E4JLFMtnaw0e25pfCn5OmxBB0JgSM0Z+JTbPqZLe/DZRk5UZfFKo2isU65DoxL0qL02ZzpB9HEsXPBjWvYtMwjJUIC1G558GFnP7UzLpKelF6MTjmYoVKWVCPldOzQJBfNHCHIzlwXqJ0Z40ay6eXpkCBIrR1l0LrP6DPBag4eySly1/4L4x7H+8e9rdNrhKCtEBDd89A9/3iVTwR9KusMKMl9xn/CgzFjXcejHe2KZejCrgDniIdHQI2i0ONrv7TVhMmIhXnGMxUiwH5RF690fFboqGMea/hNM+e6FU90yXqZCEJmX+WeziVxNpXcMjrUcgHfWAaKZ9OXGxqYgheJVT0s9bTDSTffpp5qtmHuxnRTaivuoWpeET6WCI3w90v+x9fhPYBcmGF1QYBmH+nj6ytNQUdLc8nhtoBNwB8L+UHriCN18iEfp7UUUtW1dH67ijowm07zrDTEa7YyzbHtef0lE6U9nblf6Bq7gLdU/nKQRpL4Bq8vrtlq+FPykg4WBLfZk+5IJKoq6ojlQp6qJNLpopgJVxGXd0A3goAZMOhBRBl/DKMP6DM4NYxWIg9lxjvF2EEVKV3aEHdBGx5WwsYTYygPftWRFei/TAG3NIj7Yahsh2c4DGI0uZxC+I/TYqIEhJAdcgKXB5ZqQ0TJXqhExOuI7sI4SRRcv7U6M8KtygKSP8v5uxrxORzb60KVmhsBm83B+/5QCK9WPjibm0ndRLSOaZA1z6fXm2Hy4BL0q9XQPW3hFQfnIjQ47C/UgK1qDdFLXy4CczE8j8p/VtQc2dVN1q6fmffOvIwbzh0I0MJge4uL2bRVJoSzlL/WliTLECKBJQ8qnXFqD9J0EGbLfFrxVMWa9pBnrpI6bbYs+CzUlPZOVjMg9slXptxpZxuWC+cX/lMo83CuPPAdpp8sVvF+Bu0mVvmdPi6RwCnk

# updated secrets
serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31177

service:
  type: ClusterIP
  port: 80

serviceAdminer:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressAdminer:
  enabled: false
  # className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminer.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


adminer:
  port: 30881
  
resources:
  requests:
    memory: 2Gi
    cpu: 256m
  limits:
    memory: 6Gi
    cpu: 1024m

storageSettings:
  storageClassName: local-path
  accessModes: ReadWriteOnce
  diskSize: 20Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80

deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

disableDefaultNodeSelector: false

affinity: {}
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #                 - ssd

