service_name: wsl

targetCluster: k3s1
targetEnv: prod
targetNS: prod

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: production

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: AgBOno9brRRCuh5mn1ushRH8M9MhrKWWPmJLcfOmwDV6WOf/TIeZXmkt3UQXoSUuVMzk6oDtAnvInCvevHKCteV39JhTplySlLMbvg0XuQHZmhovKapddp5HQSIyLNfokxskMCGK3BWix32xdJzr0b6IucCcef/LvZD2rXQBVf2CdvwxnVsCfi+BcX/GLQml45QsyJq+ZOkCyr4hB4WHeO5gNY1Fxgg7DSZXNb7fEAB2ByIzdWu9nBGdI5dCJHQ1xLSzY54uw6pyPliLA/Tq5CyN2nsIMqCDRfzrsjpb+1SqJa9Aj+ZMg5GMOVBcMDF/V/CYbqQVgOZmXFGxqVqo8emZpWyUvHVYGCc/qix+TDqJfjrq5igcAakE4C8M3HG8eAd1TSr6THdSS/W1S/wGV9qEcb3pYQkAAq/1BJguoLIDnRe6sNx52jNtigSLS59vs445P3qvL3PhF7D/gPo1ARajMNF8FEFXHEXtZk+PITQ9ji8oRO8SPFaWsZ/acUn5vM4VvjoAMYnTps7SX8p+N69G8Vnu4VCr3I0WAEP8kb3+/yz0a2Gm9NQfo3ICDAmKGq6WZB1iLAU+yae31m/DO8dIU/8ubzUpjuHDs6gzFBL5mJzmlaoFN+mkDmSq1MMSNNy4Da1S+tSzHKHCcK9xuCXG/nfokFzjIklXmRW+iV+6TMevZjRyfISHucjJc0Uci1aoqcriiye+iJgmsUPb5NXkTHs2PjmUnTTyTvcwc+GU/VA0BNDUMRtvPWlMFEAfngjHb7VibqCrT2HK8vMiL0n92JnyWe8ErFBB0NXKYg1j+rr9O+GOXpkKJuhv2tJolhJc8UnztYWbghM0ZJa7yTlfJ6wFZMA2FEKH4CTbca4dbKLx/idOTi+UQ+coVXlhICy76TnlDZGMpqsUs59zNoHZX7FUu+o9XVkj/z6nhG/R/St0MKu7wTBXOxKGgp+AXmkxvAifzxouDxZJecjgwAh/2deHkWu6WQ3LocIQMEmmdjoYX8svXCu3aPhEoDk9rXjY792rCyIyl2y7TtfkOphqDz05/CXLxsXC+DOanvdzdrSz+LFsdRNUOhAX2BBDsUCr13Qhmfc78KejMn287tIC0HaRzF6fvwInT+JjEr+mt9p2LFdHWgbP0cttyVxDimeM6goVaWDAxEQuVkgDP8kQaAyoWvtvo7kWebNifN97I76qSUvHwvO8WkKLvwRLW73br7dCfRS1rtBNMosMMdXfBmAZDdOIYmijQCcsR/E1Az9DOY5v6AR+sNcU6QZlP2l29ZKncQX7uq3dHO9nlBfr5KfJC4H5lpY5ciVurfXBPzMLgFn0I9H4gLca5NCcSiOEDdPfRSv/nVzn9EXxHiPwEJWtBkTO4EpCHap9ZopWVxuv1SkpEYO5+qF0NTaD3flC+Of0JO/Og0C3bHQJxnRr8vE9MJwXR9zpsrqymrfi774gmu0pzSDg/BObU5xoUIpbR/DDH0SHpLIYliJ4q0w44CwLV2ypOo+wUSyI5aIFjRWXJwtlS2qPLReHSe/r/MYli3BsvcDZHVCkLGwhZ1tIIq3JzyEZy1fVfoWa62XIhqOfbp4XgsFeO6TsYmFhIrjXmr+pecjXIEoyVuUFP+TplGnnM4uCS7UMS2EywrsgcygdCCRqzAhhqob/ZcwGYKawxJ+xjPJ6K2iu1vSFlZ7gdzrc99TgaN2aW50ZfU9P1Gb49YHLz6l5DoDi1I/nWKRM3xJ3C3Z3yugHdVUkxOUBNDyxCm2ibT8KhvnG+Gre4VA7TlgKMix6MwmdgcioE+lFYT6iAvNFNPVyHWrRGuiSKN84VGk7Tj/0E5JSKo55mOrJ7XO0Kl+y35eAnzWQESERkkQQKVnDYRJm7EAXyX/byksUW4MEA5rOaD/KLag4I9PGiSMDo4dHgKtH8eVVk0Tv30AMLLaEVsf5yzXvRt/AWs3HCdsj9mIYDWXUGBdGDAwyxJl5WZB+g3gkpRQ1M6/2Kor+Pe1BTCp+jpQ7++aQi6vq5aCwNJjUmeELUCQBEPE3XBnFNC4kOkiQoIrVBWNQ+76eRY7c0Rw7Ozg0S1PVcIStZMBk4lqPyz8OpG/zAxGt1AbHkFCi+q3q4bKsHRcJ7KJfJK2arFnHH1nveVZ876KzjZ1ALed+7koOTzurYOqNYxKNHNkTcaeF2skjUt6AwX9/bG00saERl20x3I6JIBOCPn8UgHn7SKJ5KN3sJoM6FvtNq8bzZR/BJ7Pnt5OtowM6637nXJCOnseUwnQPgkSbcHMz29t1oLwRJA9G+pE/nAqb76KE3p4i9pw7psPRor/cGUPSG1HE79zfWcY5g5Z+ti9nD/urx3/WtDvA7jU8as/IUCgHK1EPSDJv0P+O9F7Ali2akskwmln7UxD8+tyrBOcOhMGaiKs0kFxtOOCp8td/eJm+SfOfmPsrN6lSiOltIFNiqaz3gLO1ZOs7NiPlcIx3PGHPPbu0H5JRrLS2NTNWViE553ixtsKtgu3TFJECQ5w1KX6a40GrA6Ofy3NUrXAIxCFIZ1uWi/GlAD0IPVyNkVgEfq892Ly7GlduystVD3V06CDRRA0/t9EwJEJQdB/HVzzTh/h7azmmcYc5VsSDCkWQTvgFzrQa7q1kliqOk10LDCUH0TSVPhmNwNTKQZKnyq0uyAQhSvDkHtqnvTr4zPmUme4tN0xuZibEZygOtRVMqdMggAJwAh+gOOl6BdCCnpmJ5KUDOOZmz+WHmp1cRhDdmLyJbUdG93EIZ5O4WX9Zvt7WEN8FGDj1iHuRQ2WObtzfse8Qpf2XSlBvxZK69cOTyplhU3ClqDXeFyLNux9MRS1AtVYjaI+FIn/kbK6tpcq4devPXQC1EPuDz/O7RlzAHS28dJHzQMrL3c/u8qXS7hWAup+YRu3NNwaJ0SUegFbTXDuiv7W64PqqkvoI2/GRt/ev8WiRrM0NHKKNgQ+DN7JdgppYZSN8YeTQkBS5YMCOI47OvriQB5dgUrTL4Ta+B5UEl0G0s+FXyYsFv/IndIDLT5fHd7zdV97hyvstl/Y5hrQDyyJ3S7KZB7FA2jkUoxyISXA06+PSDKEXU+4SbkwLpTVNfdxU4v4Q31vST8DKdx0JuqbekAS+qXosblAEg1HJHL+dY+Y5J7ce+8oB/xG73tW/ch3zSiXYXvxQeS8rIV+irrwWmVbx9ngDHT/6+gXSJXy/4ywBKTxGN0Vrm1ZpNyd9NlgvwEriyOvqKgPse1zgrIxTNBZNF1mAGh7D/BrbTqm5CytWpnhZmPaXLlHRPNLMmUfe15YZIgP3NhJEoxXNL7VWAoI/swu4jggQA80+/uuoHuJyjnyqAUnZ8MIYZE0FW+agooZDH40irjkWEihh8gSp60Hkfs8y7UTfYRtSpAVdbFxkVTmfIpucs5QN5AWHLyinToR8UdpfeDYpaQmh2/vGUNk+kWRlDlbtdNl1pCfpRaCPyiF/s5nPD1iW4Obieh14Kzp3Yep/fEU0c7NqdJ28n8Tja0fYH3Q03xgXjsHvoUoKTi06iUqULBRJ8DPm8wQDJTDAr4McMf26dUVP3hTd1d7+2HfY3E3OVnJDKTg0VbxdwftJsIEwNJsCgzVBq6cM6MfHpaB22CTnfb89N2g8UgMyt6dRfFPnJQGsgY3BrQO0UKoXhxDL99uqslZkiLTlB/6gOuhLEqacJZhRQa5PxekEZMGmK7N9bDJdAsTAqOEJHA9xrqKZMdpAnxdKKVSGb7sJLYR2F6tn1S5/Uex/1zWDRiwpL2/q6PQ3lCDg8VQCPx5Rmj1pB0rdxcaUu8XprTX+kpnYV7hjM0BUOoPryi4GMGQgH6zT2t6B5zqg2VLxCHGWJMYTHnI8/mHMONDz1nkHJCxyby53tP4mJm2EleIpDoM/rqcAWN3E7hgg3J9LYSXJth7zjlWBSw6nfhiyGQILJZv5AzEthYHO78gYeWWX7yHzxFGqEQD96leqHRziLRZB6hjmRtDX4pbvaZKEXtX3OJLUVQiDCMPKjTiNp8UHQyrbMJSMq/72Zt0Wuw7U/ltCFFJJSJldnKw21Cz0vB0ldPnLhYXsJR3W/sJJt8cPIYscHwSN/oLBccCaXnhB3LAu90BVQk9K9CBZimc5ihjqVys8gF6Hl4mo2PDiakcz6qtj236a/hjzpzv+1UPy5JynIjFRJTGxn3sKDgwwwshEa6QKwmtDDgbJ4R1SJ7lWgi+DivNVxB3/Jbq0lyuokS3tZ/pkQ5h4JSsdMHLkE5NjtgFLaUPNlKasnxSqJoCBJ8LqYXdPWWjTRjxIz3Qkc9G4vs89yo6VPUTBoCvgvyvK95uI2EBy2BUfpUqdGY704ylXrchp/LrM6yZvQrzCx/rGk8FYn6oi/EZwJJRud3H/MVh4XMtxiVR+nptsccBZ3006Kzb+yFkZEEfhRDmeGLn/h2lX9QWfvA6NTr2Vl3uAQ13tX+L5dU5DU4NsQKPRu4iq1yKvlG6rEOvXeGdUZ7xTBt1cgRBIcD1ggSJpsVXA9RZQrQ4cPwq8zx0PEHKiNkbQagvxitN8B4GCMfWCZKLBMRhMT+iE/0ee8sxfSPUUEemLspMf8Aq07n9NtUZTmnsFVhy4ZcKmQFxynpFTPUESLx57m4InAxuim0ktrjKTp2mYuiLXnDVZdGbR+SmHyGjlJ4YdYjBQETCEwgrBa3B9uZwTON4DDyfW/mtapRK1Z3Q9QEnnbGw9jXTzQ7ahkPMJV0sLcYYDqS4UgpgTvRMFOIdlsTQkCXfQK9OK8T/kOHabLlwU3bYEoExk60xLgVxql8wiZvoWxlNqMZJvSUne8mph0WkO5wlqUAIFcIyKMmQRjBmJnpZZ33WsyXT/FQGDrQulNpeAPRWcJEhzQ5FkYljH5GjwA4eHWGet42tt5VpQDT16YWYKX/Opb6zX1798TjcXsq9sKVD9lHqVjeUekziVYTE5KgCzD2Sf66bQHKJASNcFL9TbfVTotQkPqq64A4Ck29O7kl33/wtdv3FiKcqkIDh1tmWhADES+fDvza3qEkSSwxMjXPWZvzjOTl6waloEGpMB/6uOK0F3WODkvsxb+LI6asCqlG1vGfkf17soS4YM1biE0D+A6herp9xnEeBQt0apiKF9jOQLmBG5RhjEVlGfYkIbnU46FOBp38NCab3/krk6iaNzG4Q0lHMV4eypLflGVsUPcIlsxKX/BFlKVdT8Pe4oBu8pJBNBK0nwD+Z7exGN3B/X83FkmvQSusxnUEsR9iWu8Oz7p9TONYb/XvM7YRRNsX2pTVehUrHkm67p64xg8TfFSN/se7IdgZESPIg5/DxgIIScn/hMaSEi0NY9bm/9rdwGrvbMGy1KqqM+lENZdVSemumGaZyBgrH/82lMQyTwLKVbDlXSHhZPEZ8H222zrCrxLBYgXPvcnym1ierWNiHGEY2Lh8gAQ/7PltMBWfGxi4cSuDCfPNSydTfqEXpADB3BnrtD9vSYcPUtlEVdO6OZVY3ppUcZOO5FZq41B4lbcEOqCYwhTO9OmO/KoTZlLURfjrspPCmTUww3wO3RahD35LUGJz68rj3K+DIJazirh0G74vKPgzmSJuNIlOHjE3lB3ULcHgNIr5/XNeYwCIuY512oktbbN8/8VlDk948ZzYVc+oYsQRKSg+mrEuDNaDPP/5OlLCJssuoIwCLShkahhRHkpCkrzl7NOhqdY5z7dG4TL0AP6wmEDugGRqLRE/6wr4zLYF2S7PdIOfgX85L1+pwYayC/pbUcgBhvlvuNux2oRsDL43mu/apAfuQpmiep3+GZ8bHo1hV1u1YkuCA5PXO9/IkQq/2iPfgKVODA8aeVefvltPbFaWlh/k/70sgNd8KtFqFNfxiaclqGzclXE1SnVyjunkxCEmhfh3qx94bY+3OPeuHaJvyQIJLGAx68fka88+RPlh01xRghIuTqHl8KpsSxuqp6+EYwDW+7a8wTj7RvWi/ixlrjL1VJSsuWeg6u6ganEqj3aP/b0mYxP+WMnWyfIok853ywhPNi8/8ndd8TWzmvATbSEN3qYH0wPj9sR2sX27TAqho3V1bw4XM6aJbs98hLdaUFINzao3emVd56hzAhXVGVYceETLB1/9udJqR33MfmnmSDw4riMgatvs1YJjsXxdPgg4lnvs3nQsiLU1fs4qczbkw92zvkIjtyoIfKB2NxNzesSC3YZ/wQqDH03nu0n6+p+uz/16xWLXR3cy+TAKwYmHiVwJIXVcM7b2PyHIhpO/PliLl4vhwSBPEwS2wwnQKxgORVbL66ykEme/3epSEdGZUL/BzzqMsBCG2QMuVKzAOfmCWVazNQuXjhXzjBbEJUDbFDkpAWLD04+t03L9U+WTVNtNYoTqAOY2nOvv2TqY570HGqrwC/G4a4oNe2ULt54HAkOEqW4bswy5sXu0bzYW5I2jMFC0Zuf4l6cjJntTOC5/Pz8ioqVRW8j+l/xdqpDSKSLkF+VVg7Z/2Wzj3yMjBaVPpdkGn2WmGRCaRaL+DGA6RglT3FWoO1qI0tR/iMMuRm7OkRgzs23SlahQAZ/7Vi+//jQm7HO8VBc0sp7ili56J1xF3aHHw6BGR3owKpSxDoRFkZFJTYOnruRkUC5lVs2KjMtW7YFvDE8kxeH6OL+3IRmkWDCQpMELjMf7oBSmKJlTUODcz6A4SSc/qdSD6cPuG8juNVxMuNnNM6lWRkulDtWdOwp7ARLwVGFTfdtxa5CTEdOg90xHRRaYgK6MWGXVtn2yU13G3Qu9ipbSS0KoJiBAtMkKQB9CVPFE51hPbW7EDN9cMMspA8u+81+9odGls24GI3KUNvIoUW0BeNZ1Qzy6Xd2LY/iJ72gxa/NuVQF1607QXGMsFk5SdVC2zuvuHkbyn/9Hw8dYCiTfezc0i1XwIcKWml4UIU+GlyiOF54HC9s+HLXpdCFsggnTeOKAm15aBSE3Rbf9ehJPOyoqChOuP3egetKvnI4L6PMdouf+qg1sUoxAtcpmpuOMTzd+pz7DE9Ou5kg6OArT8jaJb2gaXa9FBCkMo4KNfQbpSacAh7rjIh6+W+LOnMy3qwMsBE+T6FlJVGv9NnrIno5kSIvj8T0fltX9DpvEccoT56tt6ItNM7ynPLhQuyTWZ93qQAup/1DItz5irdCemuCiyFiI1+4o2Ve/nxsKMz1je2GSrjEwrY9duyNpoV3IVIs+KgC9PRuXXscDa9Tc7yauBHJv7cDYOiXyYhca0PjOqrm6UyB6pwg6Yz9n9AmdAMoq5LAd9KLBLeZL8=

# updated secrets
serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31177

# mysql / mariadb
db:
    hostname: AgCUp2kYudFsr8M9s/CUggQPgbancRBhfRR3Ex+w2JesDS6b18EOWWSxUSJr2JEMbtYrPiqavDcdPV8YjDwKjK599K+qNBY8loBc2fEYPpKHWu4hjgOppgYZW0emUbZXDAtd3rN1FRXv1YBjl6k3RfWDkiX5bGuggqu8KLbIqcn2PQN8jKsC+JbSYuY1BaQ91pRPmmqdqS60GLSExNhH+/jz4RYhFsQzySwzi49/lYc8g8VnG1TcYLY9DGegxO9t3QW6pblnw+KL0edGjNkpC85nVwNinj5K9myy7gb3cfYPEXD5duh0gifkTL+GNgT46wLEB88jx2QqvTEZCg7BTWA6O36DFkcQPRPXJUlIxsVxYUg1sy8o8AhTQiUG/7Xw97T3rcNYYh9RyBft1/GSMLh6ImNGUwH3sAXN3JM59HsONcS0a86GcOdi/GXP2GOi56CTTFL36xJQFoY9sqdtccwMPceAQtXd1TAReQbUDvDQl4rSElM80u+E2rZ/OioNrXwNq2yF3EvMJ1ncP2uwbow9hvLNxpk1xGTwaYIGAdKRNdvLRCW06iMMPbX9b9ypOxyWpz1fu3czdSFatN57XJGBL4sKHoMYlD5Yc7AATVp8QkUwc+yH+ExnZMaNmeEf7yu4HTZoyGVCbeHNV6Ge1mI/yWgkiXArtgtC8ApYOQnxB10AiyknCEQnzbNAF0hUVNeDj6Es9z0ijRLv8avj
    password: AgC7QQ4ME4My0BWUW37dELN2Om+FUGNO/F6MhAk5Z6DvjDwkNBfb5aG6S85Ma7YZaRf/NY1XwpVC1L5WjYf4iP0sM2DhJI/f6HwEbHdmqg7NrcOxeJHhApnENc/xm9qTkmC6rNdR5D5WpUHPGgk+sDtJzZSTev6DcpDSAeY8JlEpBSZ/q2QrcIIdiNj6O1kDl+osMyuhMl0DC9AhgC/XT3zFZbbYwuEidr1WCziyLLX1JXy7q6WXTJ99evdaGTjBUuAgoXYufjy7l0SIRLWvgkGavYYiFPJLeF+/VBL9JZW66yRevWXtCalyvvwVvJAaIhCCepe78P1wDvDPXueIEJtbazGMjcFiC78ltbWJivAOzDubCFF2NZDxOF42irNaGyH/LI4NXi7gCre4OcIJN3lRKTz49mrsetHg51wULiMIFcIVyzvsfE3kEqg/ZcwIcStAwTRUsw0Wk8TppoAJWllxD1U/bUpxgP6jUVRjBGSL+//R/W5EZUZ1mHARSgyHlElpVEz2/iIP7m37Li2eMgKskMyXwHX708GwWMHFrd6GZMtGsQ+/KgfcOx0cVPO8mEnd64Ovaz/qZgMWe2oTJlfqqsvBrbbrF+aBmpzWq3qDKpW8QqBZu4sJ1Mtc8qw2AJKZZIosTM6QAmH4XZNmlyWshkMCWDW0QChkWBj2oSUBJfphYqO+v4EIVhXM0LIbUfpdv8hNhBDAkWM=
    port: AgA6YJdg+tq3/z3sNQeF4nPC32JByfx7vbdqULEQabgpzoc4h2zzDvG1KYPI/VeAA6FsqZllIAGnoPIfksMSWdJ/+WwTDgATQ/WgboH2CqK5WVtVJaZ+sKcmUHth9ubb8jJNvxj/ITQXuvHCFQY+U17cuw0ZgyLFWurTSfLjd8td7/CnCIvjb4ecw6oc2gXswlUkDfi8TXcq82qMWcNbrW4ZrVcT0Cu6hcrwCxuSlAyDX+lBrRlU9puME+x203Ck8F0msDti+PrfA0fd4Anf551dpIpfzYf3uaQ2WzNY2OqAhbRKtwIh5m4JqqcMVlLUY+eUc0huXiv3Qfdz7VPVftrmQrZeo93om6cTCHULt85MRjpYlogTPvvL1mj2imSKR4qVVUljyB6Yn84cw0XblVlwwVPn3xlrB1PiParb4U1z0lCRSwnrSXbIdXwXQ/rsDzwLw4HbVho4K3ZRgDNzbbWVsI51WlPot4GXKWI5lMzNSo1alzXIMQe1V25K9+wGk3YHdzhhuEoEBEAL9edmXIHDQrM7qP2RssHiorY/SOsOR/5Ah2IjfCUze9H9Qyfm6I/8dO0z0aipfYulHd3JGLUc0X+cxdc12wpZFmTWz4HXRa0mgFz2g+adOMm0HCa/O65B3olG6Gc7ASGgYs1i0TYRQ6NqzDbL1Aw1amgCD8pF0Qr0QnMGOHJyJ4ZNT2AkEU3XE+hrFA==
    root-password: AgAi0p5lroF26KAWPqrilXryj7IacNiaxXZAGgDTratQBBxKhi10rP/XWLvyVlz7njo1j2P0QBbngANUkMnMlCFQkdN6dtb2vmFn7tsZSeWzLLPzzlZx6/Bxh50ieLsvyo9RLHndncjVKBOYdiWlAgPUj4q68fWgvZN54iWjFhoZmbIUw+W/sDiVgRfRuHv1ESjesGsB1j76Pn+mJK/CKvJePHqhr6ylMXJJgrO6+i+w5lbFHBUhM3O/bWwCWxtBWjKQk9SmB09vhNhfW4x+Qm5++G9Wu5YFSPwW89+X5tsRN16nJuiIc9bVteMcB0D+dB2IUTA7DDTDUZWjb8ohZSqArxX837+c7WVji6n7tt3Ot3l47HdIdIpx4gEB6daZydLuKShm1agl696u7pUR09HH26Lt45QToNBxmn2/J4lHvif9gHYYQDTnOxPLRwGT8RkLa8MQHvwrn5QUNkV9wQMRD5FH+3tg4xJ6SOjD/Tp+gKyh79TTdb6eLBzNMs/vkIQmIYViFCvoGKAkoLA2sJkMa8XkWQXDALqarT1npHJOI8vS3CgBYP4JoFHlSSJWJ5OfA9WPyl6UeSoHMhSsga0G1Jjhp0Mt9YCvsLWYMp7QAL8Iq6g5NXsiBuM8oJd5uDfj2SAT/GVhmQq5A3NT0lIxqmF3BpeUR1ZqeswdUmJMr0x3cSL00gHiwyF7q/9e8AMvaxgh4SXjclibUQ==
    username: AgBDOsju+L0ezoJlPApQ/03sQVhfX/YoZ6Nr+5xg+WifVURDjFGA7Nkt1dVi3hBgdPgnTQ5vLFM0SNn19dWgGojPoi680JjWBgQOJxXwdbhrnImfNzcxmUAJHe5STZbqhegRZomNgTrUY/ngyM8lpvgPalTV2Y3kuZWyOsdkmbMAUu8zWfn066+vbAAD6ezQOprVJPjyAt80tkmeeIeXo3a4vin8xzoJnhD6sl19tHDzDekOYE3sXIt/viAWJ/DYXod0BKtAX35EYqyVcx+deqt5VHAe3i34IL8CmN/UhsXhHpHBYLNhFRdru0COEHULkCttNZeNZfyO7fzCMQBrGyYI0ooD1+sARQruC91eSI7zQfTnMM0QTFEiQmE1O7ndrY1QElusKz4u1gjF8UzfR2xWb3R55jJCrWrTsg5BHx3XAOSkKmjCt4DwRuxqJC5oMLGnP7Tbfs4eQ16JBhNK5SVSfb/1+uHPgo54jGNFrpQiPa10w5Ti1/E/89B8HydIxDl2dAGaDSwB5XjUXG2jrywiWz1udlTe6aMqy44lv3jhTbjRF+h+ZyWkOoTfw8OSL8bT4A4Wnsw+DQGPSAxEsalyIIq18VCXatJyGAD8B0E1jwbHShd8zvarwEcW04UHeh81SfK5741Dmq946LlECu13XIBOXD4xflAMUsYEsPuSgy2ahu9nK/tf+/8C5V1gphHJt0VshQO64fs=

service:
  type: ClusterIP
  port: 80

serviceAdminer:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressAdminer:
  enabled: false
  # className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminer.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


adminer:
  port: 30881
  
resources:
  requests:
    memory: 2Gi
    cpu: 256m
  limits:
    memory: 6Gi
    cpu: 1024m

storageSettings:
  storageClassName: local-path
  accessModes: ReadWriteOnce
  diskSize: 20Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80

deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

disableDefaultNodeSelector: false

affinity: {}
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #                 - ssd

