service_name: wsl

targetCluster: k3s1
targetEnv: prod
targetNS: prod

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: production

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: AgB1wijuIDfwQih2+0Zu6ikdHwa2PT8j5xAvWymL9GwWTBVbZzfsqCVUbYnytpen89P7JO7TnqoaHQy/SngXHQ3XElXxZazimelKzIDksi3YPO8CqvMaWPqcBZb/xAQO2e7/OAEQuomHWYl5/zGHaJjnYD6x2sQbv4kaQEjpSUbC4vIM4LjP+FbrqAU/jtG4RxnCvtwzJtblIMdmnEGT2Yw3Rp47SINYwwmxL8ZILm7b9n2qMeFk1LDtpNu2o8VnuWQDx1U0jhp7F70kNkVNGJvwiwFT5pnxyAEie+vRaLFlQ9+XTqaduBPoGDcC+qarhX2N5c2OCzafDZ6Fdd+aEU9FT7lIQ+wB+8fu+GGoa+c2LO8B/6L0bAgJI6hF2gBB708vm22Mpf4H95Gg823gwkCw+BnxAHhbIgPFur+yby4yVNBjZl0Vm6wgj7r4ULQQx+g9060uBMcoJycdFptMvYp5qGnTUTOwwwQovME84q8uRkX5Py9wRUYU0FkfESBmqahZWbRr3gd/NwLpxCdC2e1+Cln9kcpLZBHLKThLT76/5myMWTZ7z7cQkUCBbgfLI9py8kPZJCXfAquJ9aqKtudS2nANZ5vMQhenaKILwMARNCwURO4eo4wM+ScEckFij7XLP4q7CmvdN6RuZOiITxUaMMDvh/tqcuXYYRq7+VlGU2THPqGu6ESrY2TdGXRd/lcEDdDZ1dqBRAIkD0zH/kKjjriHAY2mdIB5TQT8CplZhvdFzuGXNeQXgiNoZY3vrDGLzc5Kggm/99d8vSe4ecXTodhRl45KJB9d7IN31rzXMwbeSKpKnnGWdsJQVe6bkC4t4K22M1g8Yp3juDgsoTLGi2SEX3d0umJ3FRmrP7hw707KJ90ZCSeVQR50hz8h5WQiANQIcwcd+Ids9PIPCnLjLguNZ/3M7t4OVxnNOpra8kT3SutFPzr/uIC3+dw3B//ydG9SCihzAn1/sPOtEJKBEFclNDE+zPZHUZjn+hj//EjVO9lkfOPzDAPwDCKOD0GTKfwi80O3yMozL3RtuLHgmB5hkrTfSEU5cSt+oxWT38s1m9/ocq5Ho/D2a1jVzoj8uTp6Zhjsr4wpc1iRaOYjMjeSJb1IfKw25WJ8tcyLCrN6LF8vasutoSt157NnJF0fTXaO+lJBXVhvDh93plN2SbEdm0mLNdnUMo56dDc3Ot0xjZmJA/8Tp+T55Qj07xIslursvMt4SXEyWXprSzQmZfHqcZfQ8SsHHMioPRGCVgXclRup3cXgPJDLJUqLqvEb3j6GKfH46bKHDIhZqen8ZrhO6kbmUKT17d/wNkBFA8h8wQ36nJ/DHsYYv3qdQolmsD5voWlE/JfnT/XndcAKdIT5yr/Hwqn+r3xeHOrAR2kzQSQkcHFlVAFrCFsH9LImIUHma9V5lFQaIKvE+Ga9IweY2we+bAZLe0v7zZhoU8UkKkIDBfXeLIxfC84m7ewVCtImi8EkjxUhMCd6HXkkCUvTw/jtDe8cCsBnSfbx/E8MMs4l4ms4V3BfM6ve4mIE4c1wbmMMXT7/VRwp0tpgQBIN4Geg31GzL6iiOmAqXH53LApGN+aE9H9YvwtCLj7684R4W8bxKwG/8SsUzUc9v1U6ETwwpa113Z1nzemITaV8PJTNU8tlQWzb0rZdS/NImNTq4qgKSwtaXyiaNiGroUaAIX9MOQ6V6TxI9+OmPrUsRWKDGmcas8sPVjKVnU3meZvR7e4xCpmZQ90QdrUWLFh1SpogzfQ1vc+YAZT7ELzIIU8Ee/uBMa6hjMb8g8p0XPBdk5ruIbXmFaBaVNOQtJMdGtpa+ZtGJDj7+c/+Bbl8WIllm0k+9zFEbPXs1XSM9RSVk2hFVflx3Sy1gKHVmLLcHkcUc4OcTpHuOcaBNzZwEyIbCh8uDWn3vFh8Ck0vu/4LSBfcDqXAScP7fWiHhtyCXFN4ajLKaF2qbny15HvXTiPscagyQPGNbyJO9uBPVQTkFkywPVtn/NebCmbumoGfvPHoJuAVIZyvvcX6zjmvThHyegKSHOTx7UJ4eUKnZi7cTCHzP8fPBOeUftRVTd1RVw/ORh5NFzMhAhvo8DOKy6WeHU04Jax39Evaa7OfGDVy6H7MEN/IgLu+sY7XmzO6lOmpnxqd4XIUgCqhVKXsyPnE+9unftH1SANrHveWRvLemzxci787QcK5Hv9UIdQnTZRKnESfQndNvBEsGr9bXNxqBaIK11/36RKasqwuVtKFnpht45mS9XStiiWvH5DN9jhThwCsoCrvhq9Az/G7MkdS/V+25qAw3ocAuaCQT44HdYN3jnwz/GaLw5W/msBhd8p+7EfHlILlUMU/0iXZiux9g6wZ0eCVDJXKaf1qk4Z8ITt6/31/Sa9OgL203AnKhZ03XvxW3bW+VenLDcl6h9+20WJA9q2g/OKy9pg5zymHBqBlcPB3+r6Hes0xs3u6K+7B8giFeCms6lYohJzkGn7rTEEWYnzGQ6SLzU9aXHmU39WNDiLwUZ6osU2eEIEk9HfkSfBscxUO/ZMEilkrnnqOZDlSiEsjwl7n17lazO01oiCst7baEMe4W1qmjWpsjOWZq0yySkz/mX0Fx50pY0jjJlD8ickwodCbzxdu3j/m//OTPa8ejY8lY6K/3Fu+RUv5s0g08wB2TIRQcqHK2dCQ7JlCBtQVyzNttmWe8Ux69a75vLNYS3y6UHzVa6ODsFWlbCAKpUspSqgDU5dkjPkEGRMKDU/PpfJRmPYprkCUDZkUBnWvD0RwW8sXX6a6zdpR2cUpGs9/Iy4O0zwOJCnXTMMzne1I47ROQLjpTyDAlfcD69Vxq15laFYsaClw5XVE/lvZYhggwbWOqSGe62nhG33yIQ+rw3J3aO4JCJ035ybYhgdIkQJVBqZR6/Mj0GEhEhBQAdmH2mF6QHtsE7q7gyIP+HSaOGjgy7RVPmq6UsgYJ2S1S/uU5RbkUIOnIDju3mxVwkLXuJJcAl//3jhLFHH0/L05BRqsFhYLMs+6VfqnW5TAErEJfBmO018MPYiG11Dq8pHvJ2fo6w8qa6Qc1MSF2B5cccU7RZ3faqmU17RF7nlSWv8w0/3c0mKUZHLulMjrv4axkY7kX7kWfiFjvEPIHNf+4/7NrBNyI7LN8Z2ulaqzPsIx6K/bIEiHX/4N3mHQrcVCpSRVgbSUbM7gqL4sOUWFlvjpUGw1MprWSnly7KoZUbr5Khm1UU7XwR3as8XdBSLaz1LpeviYQNArHxIq323J2WL4D7YXyQbARbLadazsnN8bWSs97Z+RssKrdvr27Nzzo5Yj+6h0HpeetLnTpFzclObUYRVTRfWLsFVyRVRloQS1FFYlo1MBDDiIiiiDiu8kuimjIIyqjlt+WvZ27qsh+GIgyNIvTCoiiUOPCvOxs0GDJjlHc9uhwMwApq5v0kf1ZV3+5rsLEMK7ZwjEI9yfSisn+4DCMENczqTUYhdYs/XE+X3lryBYscp2DxVE5aXDwNUyXlYNykoRPHOXTio5MWX50MSiqqsBqEZuMPVnKhK5T9O07RFGFGaVXcFQkatiOxtZSXkgoUX2ulHn1eEcA6LQUjC0y1SHf0NUxRVILEy0FjNPSqzgK0HIy2BXjG47r8Xlb6anITNEXS+yFrEOhlDPu+WRH/qlek1UtvnoX3AT9TK1TY7UARxQEKPCd87NrwbiItRtym9fZUo6r+XkhrddUrLoOru/cbKDiGELzytufFnGCprkLQeTWz3/z+MoszXwbH4GfSF4Rf+6Sfkg9PP+tJln5+jcar925p6EEnMZiiHCl1862Ljy3cSAem3WooLV/PxvdMIvpjXCknKhJfm54YLZPnHrdHMBbd7HSbeYJG7030OPeM4kdKsIeaBGEGGhEQRxNP6eSt0euBD3ZujBAr//Y+SuNbdo2uiYaoB76I9kYSIvpwG6aXsqGjo6lXH70Qcj50rjtpYiTxmBPyWoBi49yNEKHsoQ9LFZhQkPsd9cqnGLIPqU1lWHc34l2t9RqUnWS0V7zZf9f7nYfO/Z2bxz/72PqKcVN0NxQDbIIa5rZ/WlOpxoiTz7u0i4Gjty6N3WnQE09ZkN8q0oFsKlkEszoJwpDhWG+1ZV8iqB5VHI24wW3wYxZpfARZ2VxaZJpT0KYh9SCnGpg95/5NZt2vOBHZs36KACTvNjHEunTkcbb6O0QRE4Lx8HO9IsKJan6+Uaom6DvBdonZNAEEj9XM/xyVx9Gk9dkeo71nZ/37QxRq27wY4FSzh0hnYOn5v6qXbIuHgiCIVJOIl3qxOz8IjiWERSCBxW4K3sKOK9CVJscNijX5gd5nCZDGD+5zgWrwAIHk8NWZFsBsClLMZGxgJjNVAwMkBRipeDlujFIEHei73s5mLe+TS9nYIjM7VCh7tT6O9aJoSwD8QWjT8RFbsncWL9Uh5HKkqbHdk7FMkcCuYzr4MbshOonsgfV2I4eYsl0/Ck6GClOcgeSsTCOziKK2WevcT5bAYo1TPFy9FoX/aHEgpGtwb+0KDcj/cfctDp88dq7lKmWtyMfnxmqwlK2Gv2l8ByLMxjcYfgOVFXHuTXEmx6eJD07O7JnbMUFCeU4ty0jAPyFnCE3lrYSHOVq77PkEv0LU0YLiaqLqfj+CvLCFIhXwuklMxjkr9lqXU19K50QS6DnEJEk/7hwrq3uyOaBIr8BNdnJB+hWG2M3M2ROWaOF5Zq9eFqiO9DeejTqf3dumH/AdLcBD2vL2bxjTQP7UH4dx90/t1bTdhC6ogh9UYc3kG/3FGWHgPHxNNyFS5u2ZAG8NviYYnXxyl7AK2QVPJvSRZKElAoFjM2rFEBWvcd7QuXymwmwuRr1lcmRVPT1hoQvsouvRLfzKhx4iVHy0UnRM2h4EwW0R8T84haq1BtrzyFMcSxXr0V1pSwUrLFVTArPXAN/UKYSQbgQX1BLvQGhWqXoC2LsFPJtUPgN9sUfBmI9yBea91dvLLvn9UM9Jj33RXhrjn7GRMDL6UGU3dD/zYb9hXAIKHV4f1p61+lhylBnADoLhDSUDcReqLzfj4RoZQLzqU5hTwdCFqsi7olQteSM6kSmMbz5jomfNt/DnQt7tG14tVzCu1y2F8hFZ0z8rm5mHDb/toTvofQFrPqmYlndaGMG0kbUWKq3gWLFgnskbmGZWRa/ifh/ZTxw7TSoWMI0xzaiR/jatNSkK/5h7gE2VPoj9B1anXegukfgqCvRDIe23WGy0UrJwWidEHuLJnGikVbkRHJpUo8V0paPlvQKhVTpwJgh2ec066ENOjMM1M5vfX5nw/1iKMpT2q4by4dZJEeKvX14i0yJc/ut2yhEkzX7gNF8Pbs7QwD+cjVRrLfY8imkPJp90x3QpjENA+Odbd1fd0fUQOQF3SuuIhBWrQ1ODADsyBMS92lM2er457dReLdxAiMHTAmuMmz6OQgwPBB9ZvAjn4GSXKnbuesTFgfyM1XkysmV8SKkkstuKqzX2eASeE9P6nrP8SjczHwKYce3qGW6VrWGFNMRhTU9EaoSfi6QFBl4mCtDLlgBMwQvjA4Yy+hxze/Q4MeR//NKvB7Wh6EnY4AqqsSoUac6RtUhao1tmwvBH3EzoMJdNqmQ8gPRqL1VswrUgb+VmVqZUnFMREP8UmmNiKBPDKstznMhEPqxkzbMxIvXw4jpmmQbeOHT/srXOAJGgS2M0Th352zZN1J2aogC64CTMpgAicDOFCowaKoMkJeZMG1NWX9tYeUDAtyrfeKhZdzuWF8tlqCv/U8lle0mg6+TvOpyQQQqzgAXqv/Crx1AvmzNM+3eUVQ64qyD0sKcdm82YBguvhzMc46zkFGyfJXdgB5B31oQRy0N5J8KjV4HCxHQZ7RlKICc4lOD4Ne+g7lAYPmpzP+9214sTnSgfZFDRuxVDS4lekmebS2pnAJVbTuHgmSPx5laL4NAnF0p+WV9aa4xCyzL48jJkvjp6UaYVw3cpqJDhiFRY5U88yWWdTh0KEJnuVGj6WwJzLJA6+6k76ihxkvBryemOW3D2QuUGupUF8M053AWo4VH0oQiuO4QeicIHWoMrtPZ3m7aJu4C3iwaPfU0hLBRLG8j0Hm3ZMxO06BFLJdtRaTZ/fowJMbalcsKfigVhdV54BDerVjSVedDDg8hNL0L1FWwMXG4wvhRdbloOrhX4h20ICXouLgdbvI/DMnQUe4bq5yorwT3qkAfipuL9sHEm6smylxO3FbEf7tpQJZRuHZ6ofk6XUpVXy6f4xcoXWVUtf/290uT7Kn8o1YaefgPsV++k9qXkYsvQx407MnivSmx4Eny9N+9m9gB9Y+q7DVl+2yeAGj99rNcGSx7WbGWsHh4QbXrlGLiFU+Zz0I3M4FBPaKT67u4uJK9s134HAT2FlJG276xCJOxFxBMo1MZOaTbwcBFPoXHK0cRedcvLhKCG6bjrzMNkAmdu8DnL9rAoE53nx/f+X3k9Y9qRhvkyTLE9/9UW6vuw9hHE0Dr/rfG+7hw9TSnVsIz/n9wXYNIVkQWYmYa7IoPZgH12ek9i5SB0TZ581wdLkd2HVAIysMDokNp9KndbQHY8knumX1nZS4XneRgyuVqJgT+Dx1pQ88HsSACZYfIIvxc90hcTeBGqovJett3spNVuUIbZmZQruwyimH0SvcnknV5v+sWCv09F20IMV7G+Gk4zleQS2ikO5E6AlFKbFuZNViQhCcEZU4cOWAMTzlWyVaxgG8iMfK6EdK73/mzY/4s5SSnzqYATioi2OWT3GwLK+7wA0kZdmvqCbHk6UzjHgpdgmkbi3c90gLuUF9O55WjeqPVhdScTF5NJWkIiNdW4Lm6p257TfIGAJCtzhEhidvH0gPof4aIYn6fxX2NqOaeyHbkV9gerMDaYv9UEFFH4SiK0t+A5mguZaHvwW2pf+N8wDw5Kthvb/X3V8b0f/okM8RWrhd+6ZTfQOSf0EBGtEUKfGLYIOkpyDrNWX5ALTafEU8rhxC7XNHnXAHHyTmLO1ZbO839DrFiMaNqqbY5Mq9Fdk+H09roapeXxBUdONbNl72EmbGYsh40Vy/jyEx6Xp06K7sioyVE565R6Vadw2vsqoWlJsaklhfARTHEcJ755/+9827tnt25rK3WtfGl529l807qDK3/+7Qu5BHP0KE77LGrq3wNXDdsSEBayIP969L2JjPOfIzfSK+o63eoq/SRa4InBXWymiy+VElUxlRqrggKiup2vOIi6fFWLO6Ya0lsFuv8IgC6AaDOkKq1FWEUDaZ1rWOQe4=

# updated secrets
serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31177

service:
  type: ClusterIP
  port: 80

serviceAdminer:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressAdminer:
  enabled: false
  # className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminer.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


adminer:
  port: 30881
  
resources:
  requests:
    memory: 2Gi
    cpu: 256m
  limits:
    memory: 6Gi
    cpu: 1024m

storageSettings:
  storageClassName: local-path
  accessModes: ReadWriteOnce
  diskSize: 20Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80

deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

disableDefaultNodeSelector: false

affinity: {}
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #                 - ssd

