service_name: wsl

targetCluster: k3s1
targetEnv: prod
targetNS: prod

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: production

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: helmfilesecretsplaceholder

# updated secrets
serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31177

# mysql / mariadb
db:
    hostname: AgCUp2kYudFsr8M9s/CUggQPgbancRBhfRR3Ex+w2JesDS6b18EOWWSxUSJr2JEMbtYrPiqavDcdPV8YjDwKjK599K+qNBY8loBc2fEYPpKHWu4hjgOppgYZW0emUbZXDAtd3rN1FRXv1YBjl6k3RfWDkiX5bGuggqu8KLbIqcn2PQN8jKsC+JbSYuY1BaQ91pRPmmqdqS60GLSExNhH+/jz4RYhFsQzySwzi49/lYc8g8VnG1TcYLY9DGegxO9t3QW6pblnw+KL0edGjNkpC85nVwNinj5K9myy7gb3cfYPEXD5duh0gifkTL+GNgT46wLEB88jx2QqvTEZCg7BTWA6O36DFkcQPRPXJUlIxsVxYUg1sy8o8AhTQiUG/7Xw97T3rcNYYh9RyBft1/GSMLh6ImNGUwH3sAXN3JM59HsONcS0a86GcOdi/GXP2GOi56CTTFL36xJQFoY9sqdtccwMPceAQtXd1TAReQbUDvDQl4rSElM80u+E2rZ/OioNrXwNq2yF3EvMJ1ncP2uwbow9hvLNxpk1xGTwaYIGAdKRNdvLRCW06iMMPbX9b9ypOxyWpz1fu3czdSFatN57XJGBL4sKHoMYlD5Yc7AATVp8QkUwc+yH+ExnZMaNmeEf7yu4HTZoyGVCbeHNV6Ge1mI/yWgkiXArtgtC8ApYOQnxB10AiyknCEQnzbNAF0hUVNeDj6Es9z0ijRLv8avj
    password: AgC7QQ4ME4My0BWUW37dELN2Om+FUGNO/F6MhAk5Z6DvjDwkNBfb5aG6S85Ma7YZaRf/NY1XwpVC1L5WjYf4iP0sM2DhJI/f6HwEbHdmqg7NrcOxeJHhApnENc/xm9qTkmC6rNdR5D5WpUHPGgk+sDtJzZSTev6DcpDSAeY8JlEpBSZ/q2QrcIIdiNj6O1kDl+osMyuhMl0DC9AhgC/XT3zFZbbYwuEidr1WCziyLLX1JXy7q6WXTJ99evdaGTjBUuAgoXYufjy7l0SIRLWvgkGavYYiFPJLeF+/VBL9JZW66yRevWXtCalyvvwVvJAaIhCCepe78P1wDvDPXueIEJtbazGMjcFiC78ltbWJivAOzDubCFF2NZDxOF42irNaGyH/LI4NXi7gCre4OcIJN3lRKTz49mrsetHg51wULiMIFcIVyzvsfE3kEqg/ZcwIcStAwTRUsw0Wk8TppoAJWllxD1U/bUpxgP6jUVRjBGSL+//R/W5EZUZ1mHARSgyHlElpVEz2/iIP7m37Li2eMgKskMyXwHX708GwWMHFrd6GZMtGsQ+/KgfcOx0cVPO8mEnd64Ovaz/qZgMWe2oTJlfqqsvBrbbrF+aBmpzWq3qDKpW8QqBZu4sJ1Mtc8qw2AJKZZIosTM6QAmH4XZNmlyWshkMCWDW0QChkWBj2oSUBJfphYqO+v4EIVhXM0LIbUfpdv8hNhBDAkWM=
    port: AgA6YJdg+tq3/z3sNQeF4nPC32JByfx7vbdqULEQabgpzoc4h2zzDvG1KYPI/VeAA6FsqZllIAGnoPIfksMSWdJ/+WwTDgATQ/WgboH2CqK5WVtVJaZ+sKcmUHth9ubb8jJNvxj/ITQXuvHCFQY+U17cuw0ZgyLFWurTSfLjd8td7/CnCIvjb4ecw6oc2gXswlUkDfi8TXcq82qMWcNbrW4ZrVcT0Cu6hcrwCxuSlAyDX+lBrRlU9puME+x203Ck8F0msDti+PrfA0fd4Anf551dpIpfzYf3uaQ2WzNY2OqAhbRKtwIh5m4JqqcMVlLUY+eUc0huXiv3Qfdz7VPVftrmQrZeo93om6cTCHULt85MRjpYlogTPvvL1mj2imSKR4qVVUljyB6Yn84cw0XblVlwwVPn3xlrB1PiParb4U1z0lCRSwnrSXbIdXwXQ/rsDzwLw4HbVho4K3ZRgDNzbbWVsI51WlPot4GXKWI5lMzNSo1alzXIMQe1V25K9+wGk3YHdzhhuEoEBEAL9edmXIHDQrM7qP2RssHiorY/SOsOR/5Ah2IjfCUze9H9Qyfm6I/8dO0z0aipfYulHd3JGLUc0X+cxdc12wpZFmTWz4HXRa0mgFz2g+adOMm0HCa/O65B3olG6Gc7ASGgYs1i0TYRQ6NqzDbL1Aw1amgCD8pF0Qr0QnMGOHJyJ4ZNT2AkEU3XE+hrFA==
    root-password: AgAi0p5lroF26KAWPqrilXryj7IacNiaxXZAGgDTratQBBxKhi10rP/XWLvyVlz7njo1j2P0QBbngANUkMnMlCFQkdN6dtb2vmFn7tsZSeWzLLPzzlZx6/Bxh50ieLsvyo9RLHndncjVKBOYdiWlAgPUj4q68fWgvZN54iWjFhoZmbIUw+W/sDiVgRfRuHv1ESjesGsB1j76Pn+mJK/CKvJePHqhr6ylMXJJgrO6+i+w5lbFHBUhM3O/bWwCWxtBWjKQk9SmB09vhNhfW4x+Qm5++G9Wu5YFSPwW89+X5tsRN16nJuiIc9bVteMcB0D+dB2IUTA7DDTDUZWjb8ohZSqArxX837+c7WVji6n7tt3Ot3l47HdIdIpx4gEB6daZydLuKShm1agl696u7pUR09HH26Lt45QToNBxmn2/J4lHvif9gHYYQDTnOxPLRwGT8RkLa8MQHvwrn5QUNkV9wQMRD5FH+3tg4xJ6SOjD/Tp+gKyh79TTdb6eLBzNMs/vkIQmIYViFCvoGKAkoLA2sJkMa8XkWQXDALqarT1npHJOI8vS3CgBYP4JoFHlSSJWJ5OfA9WPyl6UeSoHMhSsga0G1Jjhp0Mt9YCvsLWYMp7QAL8Iq6g5NXsiBuM8oJd5uDfj2SAT/GVhmQq5A3NT0lIxqmF3BpeUR1ZqeswdUmJMr0x3cSL00gHiwyF7q/9e8AMvaxgh4SXjclibUQ==
    username: AgBDOsju+L0ezoJlPApQ/03sQVhfX/YoZ6Nr+5xg+WifVURDjFGA7Nkt1dVi3hBgdPgnTQ5vLFM0SNn19dWgGojPoi680JjWBgQOJxXwdbhrnImfNzcxmUAJHe5STZbqhegRZomNgTrUY/ngyM8lpvgPalTV2Y3kuZWyOsdkmbMAUu8zWfn066+vbAAD6ezQOprVJPjyAt80tkmeeIeXo3a4vin8xzoJnhD6sl19tHDzDekOYE3sXIt/viAWJ/DYXod0BKtAX35EYqyVcx+deqt5VHAe3i34IL8CmN/UhsXhHpHBYLNhFRdru0COEHULkCttNZeNZfyO7fzCMQBrGyYI0ooD1+sARQruC91eSI7zQfTnMM0QTFEiQmE1O7ndrY1QElusKz4u1gjF8UzfR2xWb3R55jJCrWrTsg5BHx3XAOSkKmjCt4DwRuxqJC5oMLGnP7Tbfs4eQ16JBhNK5SVSfb/1+uHPgo54jGNFrpQiPa10w5Ti1/E/89B8HydIxDl2dAGaDSwB5XjUXG2jrywiWz1udlTe6aMqy44lv3jhTbjRF+h+ZyWkOoTfw8OSL8bT4A4Wnsw+DQGPSAxEsalyIIq18VCXatJyGAD8B0E1jwbHShd8zvarwEcW04UHeh81SfK5741Dmq946LlECu13XIBOXD4xflAMUsYEsPuSgy2ahu9nK/tf+/8C5V1gphHJt0VshQO64fs=

service:
  type: ClusterIP
  port: 80

serviceAdminer:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressAdminer:
  enabled: false
  # className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: adminer.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


adminer:
  port: 30881
  
resources: {}

storageSettings:
  storageClassName: longhorn
  accessModes: ReadWriteOnce
  diskSize: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80

nodeSelector:
  node: slworker00
  workload: production
  disktype: ssd
  tolerations:
    - key: "environment"
      value: "production"
    - key: "workload"
      value: "production"
affinity: {}
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #                 - ssd

