service_name: wsl

targetCluster: k3s1
targetEnv: test
targetNS: test

envPreferences:
  timeZone: Europe/London
  codeIgniterEnv: production

architecture:
  http_server_type: openresty   # apache2 | openresty are supported

targetImage: "bwalia/webimpetus"
targetImageTag: "latest"

safeSealedSecret: AgBgFLJdPqVA5vbv3+ZBt7CrrU7jQNpby8/cyxC+TEpU5HuopPtnf/JeB8CbH+uLoG0EhvxOTAQHE6rHWdlKoyxE95yNkVbksvP1Se2La9r41Vo28a0+PLPOkarXfvQeF+4bYUGTwdA//r9OIONDLWK1IB6RTfqiG5NfAaYvAkkgKtgVBWzOcC/PN+HPmdGlxqwXZqSZN52/Oe2lx4hVdamvhLNhR6DF25WO2wCxT64dACgaH78Td1tW+u/hx6s0gxb3tdYuAeQWNzlSLe1+cAWFW5qE5nsfTWF/nAAXB5naVeY1Wy5OHfJemThuJJDl2UAIYZhQCgXoYPC4OqxtI+x71Knvv42ZCeLXrfcRjVCWMJU/K3kkCd109Ahce4hDN/67Qkpn7K4b7IWJ7aDCaiDdo9o5wvvL6kLfjCmjWw83p0RF6NYFYbu3BrtzUw5xvd7dQ5/ys6Te04GazuQstx6E5TODV3eUn1PbEhm0usbm0RyEGTN9TAvms09p+deRKcqrsYuSAMPeHTxt2ziP1oVmsT4KmAJAKh9/JNQbBh+0ZwcvEchjvflskvjEeygGCIYOMI7jpfiEAPs7cC2rRl1mOXZR4xBLUswSpCrb5Djmqyw6w+Rwnw15dgvqTHsfWfpzVPest2Ee1SWrr0KuXhidAzHPkHVmL2s4WmDv4xpfdynjJDMjovwAgfKLmasVdmLjeptrxNBjE/wlnbao40QtAS++kDSCs1qmu+zRo9hF9+WEgDZryBu0P3udKHO2CkWKWX61cC6fdJj/9aGpd+XUZAR9YiWld4Ehuk1qdo2wxZKN0d9VJaeLHuXQD6Lg4PA63kCTTRS6TsmfQVmAL/xutcv2BqFF2V+DaJM5rtp/uOuZJKsSB5d4ZkEeSAyeWnEpA7MyNuEaegh5YSsBi+BAjjAoKQoFwHz02+ccM9F81D+q1PRUh9UcPebJlBpBm+NFTGo/PVPDxRwEMxT5svUaEbaQNtbglB69EMWMXhjN75wth77fltvgeR40ak6CEr4dUT3Zh0Q+XvYgLN4TBepebcgw6qNvEnVrTjsd62nBhB/wtWGoEpyrSTtfuKXJJXm4sZmUEuPTHrVDURtf4swHAOpykovBH2lMwvEWXZuDWuG4MePLdAErlsxcFqYldE491tmDiuu+Rxo2mNdg1RFD8Tf1uLUMQ/neTwBnkoWCwiasd0pAmERsbrRwwA+/Jnp7KctZIG+/8EBG0JIsrFkvnHZ8qqylhgLVYQl7XT9qqHNhQrO2FU7d3bwC3hu2eTyAsrtTeo4dH16sUkngISD+YkQe55P3eFYRzMXJ0MymnrL0O1t7QG6seWmByOYds34zb7FqSKsjGpOfzqDkIYQlbmlYF+2/K6fj4IRqLMLZqzNSNcE6EmKudDQbCTKwOnDKWXcc80vZP6VW2JCEnG4mgdgAw38ade23gR7OBJCae6o7kVeMDOBDCKdH5N+HGsV3FYeupeZF6W3l4Vh9jlftgxygs8BQWxMs6+Cqmhw9Lop+pjNeq5zaM7P3WK7MljJ/eLIjV8tvXaveB2MCuGtWFOCgXeuu1hhxY+PCzkn3GMU15sNx+tDHHRO0/fWHUgku3Q+q6mV+jSWrj/nuSGV3UNHrz7Tg5aNd4KUKFaZ1ZmC2RTOP8oqQQxTWqyFKkU7RRsaKhaxdKmyZteV39nkDZ+/mu2PaYHBvWAaVW34ceg60nQkMXvaVKk79F6a5vNbOe6GtOT8+qKEyxF4l8qEw3Xq+hoEMx9NmaGGEW/6fLktVyd8+vFxqLDlEnZ/HbH+KRvGztPZtOORAqtztsWVzsloT8r8J/3Os190IB+n5ipkgaKOcDokYKEyeizUNEJ6732IExErtxbZ7vq5hSK2UJAXnKwuPDyOFXQCCVsGRDRvqLSVJueKaxPqp21uUzry9E8TTGiznVZ+H5uLKZx832MnjOERMPq2Gb7azLhXt9a5tBxl5lzLtWQ6SR4cHT7/fnEg55mqbgpbSS3FEqXB7s32JE/A7uxP7Ri0E35yeQiIoHO6d7MSlyKlz8xJTe3cU2fF8XojHapeJRj5rL4sJOPrxxYvapLPxU4dgUikrsupmLxNZyLb8VdPv6BvmMq+1xPayXYxYpXLFLshr0CtzGldaPQ1Pr1po6aHqkuOwmL1IclAO5hLfAeS8Mh5hnemfVgiW2QZlQ2wruFfm3xDE2FrJ9WjLY1+Qww4Jly+eQ0Bhd4Zggfz2D9lQIv8FBJZRAKcY9ghK9oHUYmOdziuZ13OlFkrH2VPN6bm1qZVmgblbvw04iCoQ9t+CRUOSuxyT6KujNeIlWHcn+BDGnzjxzR2H1lP1eeJs2Bg/iqu0yZEe9v32q+KmOccDTDVb/EQ8SmEtOJoLEkJ5trIjB+VpXogXzrl6jLlhiG0VLZaKJGAec3heJwvOshzQA2SWjlRNSdZRYdI8sBCMnIhjS2IYAmCjL23TCfJjyN3tSey2p12DjXtHlS1y1RHRcI/0m3CeLFPQdPfPmw9wUbfUy5bHi5hYUuCNl0ZByUpJ8bA9Z+IXvqs/FuTN461ijhMZymE39CZVvnJYyxlf3IflZlC+Mi4NTwm3FtAD3ELWNhlrSQJ/VoJhlfWe0lj1aCHKD6iXLoxvs+PrpsmwUiRBVanEXsYc3Agxj336LoYXb63ZhJIFkmnvXOk56qU1i4I8OWHxs4b8QnAIi/5LsvRwrCjQeOXt2jY1tN6aU+wgPIutJ4sIXfT85AndhkfEpLBi6Mcn4j4wnAZND3LAA13vQwWuVxSlTGqc8D9+3OKDZMwKVAihJYVvtRRE4qaLhYpsaBYJDq0+Deyt37SBd0s5RzRUya0LLxLg7wlHori8208ZFPiZD+wXVVFA4VS88VVTugbSuYeGv/fAxmDxCHedIQESjeZ0OZQXWdvpujchqUnBWMQqaY7KcvSv/jNMpOOMUun9djCKxtBO5fF0qwGKkE7eNCiiTJYvhd0QI7vj+HuDDF035D8lb9s2P6zeN6x2PnHEatjRgETxu1PlQdo+QFDZ92FUT8ZK/1Kt/kejIjPEgqXfv5G0Agh+rS4FId0ns9vrpEEdCrJsGfJLvAHhdfC3jjTl+UwKkqUOCcsky3JI55wvTYF+Ca/CIHs2d3hHwwDAra/ENORURj7/P6+88Wk8NWNnCWUcJTHy/QbmEIC2aTvLhYvWZa6E4/8vaC1vr+NXfR7a33TXNBInFyVy+Xw6g2ah/ns+DG8tkplmvb7IeKj61dzYvAp6m3AXbg5ItuHKy8aAAKlS8bp46hTCxcegPUbF/x84oSzBABGBzyHhy/Ivbh+EYhw4KDs0Gz7Kkys00hoTvuAh2hZvkZGxzHN4EkeQFVlmpZTCUz89trPXZtYcQkCTG5bL5AGOgVqTdIiz4+sAGKbP7FnJBmGwnaKDQDrBuL7rbh/DnTQxsQ3Ww2NXeyLRsMehEQ/qQkr9Yuxdi2dN2exW0e3if845NF/ODu2GbuwTn3yNRhxsh7BpPlfQwZhJbQ/KRrYttzBW4uVvLuziSfvOe9I87hSVmGst4VYd+fxV7C1IYnbsXprmslR3yxsBbswSHqI0XpL8ry3s/2vF5YwKhBH7TK4FBhO3NdDZtcPD8Fox9kNoPfki8m5s4CUjEAry/qlvKZLDJENHD1jpTDha2qdqN+EEsOhrAvCBygAM0bziWIhx3Z79EecJ1SIv2EOZsZNK2teyem7gneTPUnWWZzClSuAZ9AjlALqX4+B0z5Ub/PZ3X5nknECQ5joTx7kTR/2hhDfoMnWISOLL1oA03GQ0KHBPI9+Dhor8dN4RNnhmq9wDNxsTBLHO1Uo1LbTaqs5tMnCP1VxWZLInthDuZNXb+Gcr4feK+TvPsj99bi1Zu6xhpZPJevUH4/yGEpgq1P33wuNVuWOa8cTNKwvpWb8bEa0Rzccbirynoczi9zB9Fauf7KNrUHAPdDLZaDTQNe30jKxdqWEql3NRvu9m+7IZ/90/VELtz/qLf6IuMvKG+q0C3FgjVEfTDN5DQqiQFIjSYRq5Wipo5aT+dncgsFMBAwFkyu51DZ5XbtHotnf3dQFek7Ksqde7PCLT7TXhP8bkh/eThQGvr1zQC07vDlN7v5/Vejxf/wfvekWgds6amzwkIMRnk47U2F2LkuMI4RvNZt30/erQb3kDJupIIeWjpRsuZOrAHxboCqPn/Sa4cfy9ozwfpN3jXJCMPWf1A6zT0ZLCubThACKKNu1ZFZ4Ri9r42ZvcaodGU1B5S6CteYTMaAQSi/MHPU3JYMn42B9njLy4XiI/pFJo81UmB4/6173ZX/oYpVz1ESJgDpqtFlkEvCSzvrSLnHQh30V9ss6zTCtsptc31W3whkIXkCG1hZ2nhm3/DkJ1A2VLVd1E9J0sqYPzdgknmkp4lzpAAvs63VuqLPJbij873RWDzwGyw34wR28RwpGAyQSpOt+vbib/3xtI8h7bBCFtm4XnDZK0iviS2aeO8XlY5nFk6UtRFl1dwRhA/CZcT+LgHzV75OmfqIvVYVBxlcj1rVd/BIjbFSpowopA9gkKMY7gqTzmGIPRp98Q/U81kpjLUsc5QCGHebmC8Xqz+lple6Qc3N6hYCo0EptoHTuPfJwfwmdNXngQ9Aj0BvVJhGqh8MeIowxImZ50UCwhiADGZC5zM/Njvn0APEZxqfYA3Y+IYVKwOepPzBiFj0mp3OUuxXvgGDWYiFcN+tJskBvF8Sm7xdfYvaZHIUSpRRPv679uay/9XVFOQ5EIKl0vcZBSnA5mIRY/snWRj2zip/u/Fa451HJyyJs2aFTKkqwr4c0bF2OOWFMw0Mj0qsgXGLayu+Tug+wAbEe5m23Q1gMtFjzcssFS6DiCtxAS0Bz+NvWmmYqIspXc1yMUMGgiyJ/FCPDhvGfMBuGmJtcTfk2ge5mxu97eooMR6Fl4ffKSTj1C7Z60x65AC/iHyadYgFPf9Ns1EvZ9VnrgtUUFOxxtjne4N4CZ9l7f5KcAcoV/2lHV/Obb3XGL/jo4ofJLjgaZwDHMMgoYqePY1rKRW+ndwKL03dSrvEd+lbhtMHtKs3iVI+wsDh7+tNKZa6iF7HqocdXW9DhMPZx6Q2toP7eS3m2kiNWfauvL/CriAEZ/u+qqUdh+Mosnk3ryxlbA31lx2ckAVF8/l4GPgbNJYjea6Pu6IbMK/1Yr26Jp//JjxL+ovL1DnVlwq3FEIauOmiIoFv6OAjGI8HPSkf4uEMoGmQ3JXqS3dyN5ttoJjdBZUWmwEUN7sJmnUTOeK0SOOMICabhd+ZrXIVkGvlPjwmsfU1sFe6mgo4rGQuXEJRvrDwttEqX9YATxzFQMnVXxQcsyT9lW/efydzq0xDiFE6kEFJxhrwOm1JeOTXoJDwPVz0RVC75j3C5Y/h2cKwaAwNNe8KEjw+fTCooG7daitFzs7Ge4eeDey6gvqQk8+WZLKvysAWPFM5AbUq8a2HVFibUkrROeZRGgDLpL+n3dTBU7NsN6ukny9Ai7Z+6XoUQ00udzmhHqduN0bDx1sYRgWTiBQ+e1M91EvSqp2C4byTp2foxKWjGgI/2S+AFLiLImk7K4zu3WZ/zE8+2/ecldW3JsJ5rOrqK0ctX0bbd8n2YQhpIo8rS/4UAuXUb6kLlE82eBK65mwhAZuKvLqBaRNdQuOPhDqZlY5Zj8vieOby+BGsp2eY92xwVhjoSnw/HkRQNjBaRSrhRyaCBb4dQZnibuMDveHZSnaLTRZbe9o3V0t3auYzqUdI8Eg9R8W4DoudxUXy/AxxRPMNsqC9Jlu1Fo0HsEFAkulxrWH/xWBha8UcYPbxpi3k7ihh1GBhdJmUuiNCkXm6VRTCl/hEqdihlOjTLD9Z51AmL5eHTN+ouxSZNsh/EOvu8w0Zr/eVuCUXuPGGs84xSopWxmOBVIseh/gh3ke+ufbbFy4bWtUXZ2I1aN2u7JDy4IMoMrG6KzTYUe10FXWt8OhMTgoGPTM++oHiIeedXRqYISKKZQb6abMqESBFf7ppKVAebenAWpBEv7iCO15DE/jpC26GkNfiMYssMFenQP+IJpKIu2skql3QWUO6v0d94bjyPhDTaKTrnqe5/Fs/xIJW0+7O0KG80TpwSCc/Zg/4wAfOb15dOwMoNxvZCmfle3X4wt7zycTv0bgKJT0wF9qgNPMuafdEM6ZkukZ+622Ky0PkIUX3yDp8+pMWUTUeklA5GJjoNGJn0Mh9tr4Jz3x7sGFhhmh7+v9LI4Y7c8SzqUA3p9m1jN3+hqbujDKXmkTkeGrviVX08waEX1F5C55YCapUao+v1/0FDuqApCpGt84fnCUxpHx/0OClkXdXWVuJNmO8xJ0LqQaMyP07C424ZwHgCEYpYrCOePLsQIZhZvdgnACHeRTs0MyxoVsqKakwG3RoDmP0iGp1cIhmpmhOAaV2j+S8zOUFmsav3LlyyUzB9gN/iRFZpc10hyxR0qTZ1Q/hygkVkvVuBux+hwmwbVu1QIx0cWvloiW+TSMZ3To9XXgDXn+Wl+7KXdBm/ofKqWOAYnXT2wBGgdrQwkJ8kkZjzv3yWznF2+iNB9o4u36YFKlIzB/kUjfovvNwGfByMXkH1HiLu7QWglBPpc9ZYuMrnDsN6nyMcUHqz1ntuMFEcfdAROeSDDVXAAMJFJdOfvHvRIWI/LQi8u9k4ZZRE62PNoHc/gYJcwnH31kAxWiIrJ47Ol7eRtbZhvioipJ1B1eE1b/QR1k6Z8ml/+KeavegFUUo6DDFNdPNdcecEdrkQMqTPgrtOrkgGhcJCfnsVKKCUe8gSRcEa4798YyPiwOK/D5ht4p6Cskhlt5AnDZEa/pa0W09Xxg7savzCi11ehDvFSO7TJtJjTFZkR7/q5j9AnvhUO7JaG4VRCnrrV1JA2+sImKfWft4SXJ0ox04Ajcg+xnXogqEiYrMqWGvUygt6Gfi5qO6T3Z5FsuIP1knASSHN37nmoU6dO1x8aAQkIzYxdDsueQ6uv8oq8u5iss+6hiClb7X1DhSA00w7j6+QrK+Hp5cphwN8Bgt3I71SGEI1lKqQCB+s3H2ouOEA1CGvCHUubxDY+Xy7Xg/4jp9ht3fYMwh7ydothl6bjUOYZx1uxfulDgrn0uU8EjHnVWmPGokjRQL+vhv+Dt/QZUq0zF4rEReK5BkBRpa8a4z3LDjLSHBuvSJ7o2C9rf8FiMg2tVPwpuFiBLxFB4xXJ3YuJGIbCC0+JQ+e3MmepXsRCT6mAkhV05vlFtliwWQHlaDn+6dYWsO+kkPnsCf6nbiYUUYtL2eYcHBvfvigCF29Vv1HYFH4jviMpsh5MoTRlc+1lEkHwKaAv+Ujom2BDqKk/drIjAMasnEKfOcg+qnuzOI+iH8X07MHh+rEERMIr1Qj9q09MClCZ8dK6UUVBYuqZUyR7MKpalQhB/B8xQ9M7HeBNYAwv99g+S7BTC/UY2WjL7tTGDxHRSoGUh7YUK6Io9lHNdVw7RPFAH6lwUAm43kUiKebf4/GbOUNewLFN87lVDzo3GhkToqRt6Rh1iaL7Fp0EMgu06OPcHo3onK+DVWfGKezlcHRpmZ+K5PkyzXsI3hTQ4E91X+bXV3v8PqWeDLZdIoZW4zi1TKV/YGjcvwrMkNV6RJKwUJn5h2PgGCHSuojBSyTey18SkVfTWKOdE+kaY4vCsJMGUE5YdK1y/LYndH1GZ/uWAzJcguhf/uv+08JqRfHQ9VbZCpwel8Wu/x0u6+OftdqfGzt7dI8L85CvtHGqjKwbCeReaBcVGS/quw5Jm4A3l/io+NVN0kioCumyzlZjK4JqKIOSu8gvMrSp5eyinipaG9L/YrsSkiAQhH0JfvaJvIctcGpxKzeoYyM5gqLY344cMqv6vTtuVuZ2dkEQzNlXqzqqJfT1jMg67uNBJCLLP0xNc3XDDClASN4KixlJIjLANiFzmoFhu+sjT8rzRF9JlDlQGwSd/Um737E4MUEyAHNEr0RYffod5si0t4lqwj2DOFIG70/gpzpg+tkIK4BIrJUMPMNqgmTvwJ2Ry69GKwmLsh17BA==

# updated secrets
serviceAccount:
  # Specifies whether a service account should be created
  create: true
# ports
svcAccessPort: 31119

# mysql / mariadb
db:
    hostname: AgCUp2kYudFsr8M9s/CUggQPgbancRBhfRR3Ex+w2JesDS6b18EOWWSxUSJr2JEMbtYrPiqavDcdPV8YjDwKjK599K+qNBY8loBc2fEYPpKHWu4hjgOppgYZW0emUbZXDAtd3rN1FRXv1YBjl6k3RfWDkiX5bGuggqu8KLbIqcn2PQN8jKsC+JbSYuY1BaQ91pRPmmqdqS60GLSExNhH+/jz4RYhFsQzySwzi49/lYc8g8VnG1TcYLY9DGegxO9t3QW6pblnw+KL0edGjNkpC85nVwNinj5K9myy7gb3cfYPEXD5duh0gifkTL+GNgT46wLEB88jx2QqvTEZCg7BTWA6O36DFkcQPRPXJUlIxsVxYUg1sy8o8AhTQiUG/7Xw97T3rcNYYh9RyBft1/GSMLh6ImNGUwH3sAXN3JM59HsONcS0a86GcOdi/GXP2GOi56CTTFL36xJQFoY9sqdtccwMPceAQtXd1TAReQbUDvDQl4rSElM80u+E2rZ/OioNrXwNq2yF3EvMJ1ncP2uwbow9hvLNxpk1xGTwaYIGAdKRNdvLRCW06iMMPbX9b9ypOxyWpz1fu3czdSFatN57XJGBL4sKHoMYlD5Yc7AATVp8QkUwc+yH+ExnZMaNmeEf7yu4HTZoyGVCbeHNV6Ge1mI/yWgkiXArtgtC8ApYOQnxB10AiyknCEQnzbNAF0hUVNeDj6Es9z0ijRLv8avj
    password: AgC7QQ4ME4My0BWUW37dELN2Om+FUGNO/F6MhAk5Z6DvjDwkNBfb5aG6S85Ma7YZaRf/NY1XwpVC1L5WjYf4iP0sM2DhJI/f6HwEbHdmqg7NrcOxeJHhApnENc/xm9qTkmC6rNdR5D5WpUHPGgk+sDtJzZSTev6DcpDSAeY8JlEpBSZ/q2QrcIIdiNj6O1kDl+osMyuhMl0DC9AhgC/XT3zFZbbYwuEidr1WCziyLLX1JXy7q6WXTJ99evdaGTjBUuAgoXYufjy7l0SIRLWvgkGavYYiFPJLeF+/VBL9JZW66yRevWXtCalyvvwVvJAaIhCCepe78P1wDvDPXueIEJtbazGMjcFiC78ltbWJivAOzDubCFF2NZDxOF42irNaGyH/LI4NXi7gCre4OcIJN3lRKTz49mrsetHg51wULiMIFcIVyzvsfE3kEqg/ZcwIcStAwTRUsw0Wk8TppoAJWllxD1U/bUpxgP6jUVRjBGSL+//R/W5EZUZ1mHARSgyHlElpVEz2/iIP7m37Li2eMgKskMyXwHX708GwWMHFrd6GZMtGsQ+/KgfcOx0cVPO8mEnd64Ovaz/qZgMWe2oTJlfqqsvBrbbrF+aBmpzWq3qDKpW8QqBZu4sJ1Mtc8qw2AJKZZIosTM6QAmH4XZNmlyWshkMCWDW0QChkWBj2oSUBJfphYqO+v4EIVhXM0LIbUfpdv8hNhBDAkWM=
    port: AgA6YJdg+tq3/z3sNQeF4nPC32JByfx7vbdqULEQabgpzoc4h2zzDvG1KYPI/VeAA6FsqZllIAGnoPIfksMSWdJ/+WwTDgATQ/WgboH2CqK5WVtVJaZ+sKcmUHth9ubb8jJNvxj/ITQXuvHCFQY+U17cuw0ZgyLFWurTSfLjd8td7/CnCIvjb4ecw6oc2gXswlUkDfi8TXcq82qMWcNbrW4ZrVcT0Cu6hcrwCxuSlAyDX+lBrRlU9puME+x203Ck8F0msDti+PrfA0fd4Anf551dpIpfzYf3uaQ2WzNY2OqAhbRKtwIh5m4JqqcMVlLUY+eUc0huXiv3Qfdz7VPVftrmQrZeo93om6cTCHULt85MRjpYlogTPvvL1mj2imSKR4qVVUljyB6Yn84cw0XblVlwwVPn3xlrB1PiParb4U1z0lCRSwnrSXbIdXwXQ/rsDzwLw4HbVho4K3ZRgDNzbbWVsI51WlPot4GXKWI5lMzNSo1alzXIMQe1V25K9+wGk3YHdzhhuEoEBEAL9edmXIHDQrM7qP2RssHiorY/SOsOR/5Ah2IjfCUze9H9Qyfm6I/8dO0z0aipfYulHd3JGLUc0X+cxdc12wpZFmTWz4HXRa0mgFz2g+adOMm0HCa/O65B3olG6Gc7ASGgYs1i0TYRQ6NqzDbL1Aw1amgCD8pF0Qr0QnMGOHJyJ4ZNT2AkEU3XE+hrFA==
    root-password: AgAi0p5lroF26KAWPqrilXryj7IacNiaxXZAGgDTratQBBxKhi10rP/XWLvyVlz7njo1j2P0QBbngANUkMnMlCFQkdN6dtb2vmFn7tsZSeWzLLPzzlZx6/Bxh50ieLsvyo9RLHndncjVKBOYdiWlAgPUj4q68fWgvZN54iWjFhoZmbIUw+W/sDiVgRfRuHv1ESjesGsB1j76Pn+mJK/CKvJePHqhr6ylMXJJgrO6+i+w5lbFHBUhM3O/bWwCWxtBWjKQk9SmB09vhNhfW4x+Qm5++G9Wu5YFSPwW89+X5tsRN16nJuiIc9bVteMcB0D+dB2IUTA7DDTDUZWjb8ohZSqArxX837+c7WVji6n7tt3Ot3l47HdIdIpx4gEB6daZydLuKShm1agl696u7pUR09HH26Lt45QToNBxmn2/J4lHvif9gHYYQDTnOxPLRwGT8RkLa8MQHvwrn5QUNkV9wQMRD5FH+3tg4xJ6SOjD/Tp+gKyh79TTdb6eLBzNMs/vkIQmIYViFCvoGKAkoLA2sJkMa8XkWQXDALqarT1npHJOI8vS3CgBYP4JoFHlSSJWJ5OfA9WPyl6UeSoHMhSsga0G1Jjhp0Mt9YCvsLWYMp7QAL8Iq6g5NXsiBuM8oJd5uDfj2SAT/GVhmQq5A3NT0lIxqmF3BpeUR1ZqeswdUmJMr0x3cSL00gHiwyF7q/9e8AMvaxgh4SXjclibUQ==
    username: AgBDOsju+L0ezoJlPApQ/03sQVhfX/YoZ6Nr+5xg+WifVURDjFGA7Nkt1dVi3hBgdPgnTQ5vLFM0SNn19dWgGojPoi680JjWBgQOJxXwdbhrnImfNzcxmUAJHe5STZbqhegRZomNgTrUY/ngyM8lpvgPalTV2Y3kuZWyOsdkmbMAUu8zWfn066+vbAAD6ezQOprVJPjyAt80tkmeeIeXo3a4vin8xzoJnhD6sl19tHDzDekOYE3sXIt/viAWJ/DYXod0BKtAX35EYqyVcx+deqt5VHAe3i34IL8CmN/UhsXhHpHBYLNhFRdru0COEHULkCttNZeNZfyO7fzCMQBrGyYI0ooD1+sARQruC91eSI7zQfTnMM0QTFEiQmE1O7ndrY1QElusKz4u1gjF8UzfR2xWb3R55jJCrWrTsg5BHx3XAOSkKmjCt4DwRuxqJC5oMLGnP7Tbfs4eQ16JBhNK5SVSfb/1+uHPgo54jGNFrpQiPa10w5Ti1/E/89B8HydIxDl2dAGaDSwB5XjUXG2jrywiWz1udlTe6aMqy44lv3jhTbjRF+h+ZyWkOoTfw8OSL8bT4A4Wnsw+DQGPSAxEsalyIIq18VCXatJyGAD8B0E1jwbHShd8zvarwEcW04UHeh81SfK5741Dmq946LlECu13XIBOXD4xflAMUsYEsPuSgy2ahu9nK/tf+/8C5V1gphHJt0VshQO64fs=

service:
  type: ClusterIP
  port: 80

serviceAdminer:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test-my.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressAdminer:
  enabled: false
  # className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test-adminer.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


adminer:
  port: 31179
  
resources:
  requests:
    memory: 2Gi
    cpu: 256m
  limits:
    memory: 4Gi
    cpu: 512m

storageSettings:
  storageClassName: local-path
  accessModes: ReadWriteOnce
  diskSize: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  maxUnavailable: 1
  targetCPUUtilizationPercentage: 80

deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

affinity: {}
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #                 - ssd

disableDefaultNodeSelector: false

