FROM python:3.9.18-bullseye

# Set the working directory in the container
WORKDIR /app

# Install necessary packages and install xvfb and wget
RUN apt-get update && apt-get upgrade -y && apt-get install -y xvfb wget

# Install Chrome
ADD 113_google-chrome-stable_current_amd64.deb .
RUN dpkg -i 113_google-chrome-stable_current_amd64.deb || apt-get -f install -y
RUN rm 113_google-chrome-stable_current_amd64.deb

# Copy the repository files to the container
COPY . /app

# Install required Python packages
RUN pip install selenium pytest python-dateutil chromedriver_autoinstaller
# Run the pytest command
CMD ["pytest", "-v", "-s"]