name: CI Helm Auto Deploy INT defaults INT but a Env of Workstation CRM

on:
  push:
    branches: [ dummy ]
  workflow_dispatch:

env:
  IMAGE_TAG: "int"
  TARGET_IMAGE_TAG: "int"
  TARGET_STACK: openresty_php
  IMAGE_NAME: workerra-ci
  TARGET_ENV: int
  minReplicas: ${{ secrets.minReplicas_test }}
  IMAGE_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  KUBECTL_CMD_FILE_EXEC_STR: "chmod +x /usr/local/bin/bootstrap-openresty.sh"
  KUBECTL_CMD_FILE_RUN_STR: "/usr/local/bin/bootstrap-openresty.sh"
  TARGET_CLUSTER: "k3s2"
  
jobs:
    build:
        runs-on: 'ubuntu-latest'
        steps:
    
        - name: Checkout this repo
          uses: actions/checkout@v3
    
        - name: short-sha
          uses: benjlevesque/short-sha@v1.2
          with:
            length: 6
    
        - run: echo $SHA
          env:
           SHA: ${{ steps.short-sha.outputs.sha }}
    
        - run: echo $SHA
          env:
           SHA: ${{ env.SHA }}
    
        - name: Build workerra-ci Docker image based on the TARGET PLATFORM Image and push to Docker Hub
          run: |
            echo "workerra-ci Docker image builder!"
            echo "Build, tag, and push image to the given Docker Registry."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
            docker build -f $(pwd)/devops/docker/Dockerfile --build-arg TAG=latest -t wsl-${{ env.TARGET_STACK }} . --no-cache
            docker tag wsl-${{ env.TARGET_STACK }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
            docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
          shell: bash
    
    deployment3:
        runs-on: 'label-ams01'
        needs: build

        steps:
            - name: Checkout this repo
              uses: actions/checkout@v3
        
            - name: Deploy workerra-ci to k3s3 VPN INT Environment
              run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "int" "k3s3" "int"

            - name: Deploy workerra-ci to k3s3 VPN TEST Environment
              run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "test" "k3s3" "test"

    deployment2:
      runs-on: 'node2'
      needs: deployment3

      steps:
          - name: Checkout this repo
            uses: actions/checkout@v3
      
          - name: Deploy workerra-ci to k3s2 VPN INT Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "int" "k3s2" "int"

          - name: Deploy workerra-ci to k3s2 VPN TEST Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "test" "k3s2" "test"

    deployment6:
      runs-on: 'node6'
      needs: deployment2

      steps:
          - name: Checkout this repo
            uses: actions/checkout@v3
      
          - name: Deploy workerra-ci to k3s6 VPN INT Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "int" "k3s6" "int"

          - name: Deploy workerra-ci to k3s6 VPN TEST Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "test" "k3s6" "test"

    deployment10:
      runs-on: 'node10'
      needs: deployment6

      steps:
          - name: Checkout this repo
            uses: actions/checkout@v3
      
          - name: Deploy workerra-ci to k3s10 VPN INT Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "int" "k3s10" "int"

          - name: Deploy workerra-ci to k3s10 VPN TEST Environment
            run: chmod +x ./deploy-workerra-ci-in-kubernetes.sh && ./deploy-workerra-ci-in-kubernetes.sh "test" "k3s10" "test"
        

          - name: Slack Notification for Workstation CRM INT & TEST release 
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: ${{ job.status }}
              SLACK_ICON: https://github.com/rtCamp.png?size=48
              SLACK_MESSAGE: 'Post Content :rocket:'
              SLACK_TITLE: Post Title
              SLACK_USERNAME: rtCamp
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

