#!/bin/bash

# Script to copy certificates from Mac to Linux
# This provides instructions and commands to transfer certificates safely

echo "=========================================="
echo "  Certificate Transfer from Mac to Linux"
echo "=========================================="
echo ""
echo "Certificates location on Mac:"
echo "  /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.crt and workstation-ca.key"
echo ""
echo "Target location on this Linux system:"
echo "  ~/.certs/ (secure hidden directory)"
echo ""

# Method 1: SCP (if Mac and Linux are on same network)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 1: Using SCP (Secure Copy)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "From your Mac terminal, run:"
echo ""
echo "  # Find this Linux machine's IP address first (run on Linux):"
echo "  hostname -I"
echo ""
echo "  # Then from Mac, copy the certificates:"
echo "  scp /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.crt and workstation-ca.key bwalia@<linux-ip>:~/.certs/"
echo ""
echo "  # Example:"
echo "  scp /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.crt and workstation-ca.key bwalia@$(hostname -I | awk '{print $1}'):~/.certs/"
echo ""

# Method 2: Manual Copy-Paste
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 2: Manual Copy-Paste (if no network access)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. On your Mac, display the certificate:"
echo "   cat /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.crt"
echo ""
echo "2. Copy the output (including -----BEGIN/END CERTIFICATE-----)"
echo ""
echo "3. On this Linux system, create the file:"
echo "   cat > ~/.certs/workstation-cert.crt << 'EOF'"
echo "   [Paste certificate content here]"
echo "   EOF"
echo ""
echo "4. Repeat for the private key:"
echo "   cat /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.key"
echo ""
echo "5. On Linux:"
echo "   cat > ~/.certs/workstation-cert.key << 'EOF'"
echo "   [Paste key content here]"
echo "   EOF"
echo ""
echo "6. If you have a chain file, repeat for:"
echo "   workstation-cert-chain.crt"
echo ""

# Method 3: USB Drive
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 3: Using USB Drive"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. On Mac, copy certificates to USB drive:"
echo "   cp /Users/balinderwalia/Documents/Work/aws_keys/workstation-cert.crt and workstation-ca.key /Volumes/USB_NAME/"
echo ""
echo "2. On Linux, mount USB and copy:"
echo "   # Find USB device (usually /dev/sdb1 or similar)"
echo "   lsblk"
echo ""
echo "   # Mount it"
echo "   sudo mount /dev/sdX1 /mnt"
echo ""
echo "   # Copy certificates"
echo "   cp /mnt/workstation-cert.crt and workstation-ca.key ~/.certs/"
echo ""
echo "   # Unmount"
echo "   sudo umount /mnt"
echo ""

# Current system info
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Current System Information"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Hostname:    $(hostname)"
echo "IP Address:  $(hostname -I | awk '{print $1}')"
echo "Username:    $(whoami)"
echo "Home Dir:    $HOME"
echo "Cert Dir:    ~/.certs"
echo ""

# After transfer commands
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After Transfer - Verify and Install"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Verify files are in ~/.certs:"
echo "   ls -lh ~/.certs/"
echo ""
echo "2. Set correct permissions:"
echo "   chmod 644 ~/.certs/*.crt"
echo "   chmod 600 ~/.certs/*.key"
echo ""
echo "3. Verify certificate:"
echo "   openssl x509 -in ~/.certs/workstation-cert.crt -noout -text | head -20"
echo ""
echo "4. Run the installation script:"
echo "   cd /home/bwalia/workerra-ci"
echo "   ./install-production-certs.sh ~/.certs"
echo ""
echo "Or install manually following: PRODUCTION_CERT_SETUP.md"
echo ""
