apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wsl-ingress-{{ .Values.targetEnv }}
  # namespace: {{ .Values.targetNS }}
  annotations:
{{- if eq .Values.ingress.className "nginx" }}
      # kubernetes.io/ingress.class: nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
{{- end }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: wsl-svc-{{ $.Values.targetEnv }}
                port:
                  number: {{ $.Values.service.port }}
              {{- else }}
              serviceName: wsl-svc-{{ $.Values.targetEnv }}
              servicePort: {{ $.Values.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
---
{{- if .Values.serviceAdminer.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer-ingress-{{ .Values.targetEnv }}
  # namespace: {{ .Values.targetNS }}
  annotations:
    #kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingressAdminer.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: adminer-svc-{{ $.Values.targetEnv }}
                port:
                  number: {{ $.Values.serviceAdminer.port }}
              {{- else }}
              serviceName: adminer-svc-{{ $.Values.targetEnv }}
              servicePort: {{ $.Values.serviceAdminer.port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
