######################################################
# Secret: Create Multiples encripted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wsl-secret-{{ .Values.targetEnv }}
  namespace: {{ .Values.targetNS }}
spec:
  encryptedData:
    env_file: {{ .Values.safeSealedSecret }}
  template:
    metadata:
      name: wsl-secret-{{ .Values.targetEnv }}
      namespace: {{ .Values.targetNS }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret-{{ .Values.targetEnv }}
  namespace: {{ .Values.targetNS }}
spec:
  encryptedData:
    hostname: {{ .Values.db.hostname }}
    password: {{ .Values.db.password }}
    port: {{ .Values.db.port }}
    root-password: {{ .Values.db.rootPassword }}
    username: {{ .Values.db.username }}
  template:
    metadata:
      name: mariadb-secret-{{ .Values.targetEnv }}
      namespace: {{ .Values.targetNS }}
    type: Opaque