name: Webimpetus API Test Suite
on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
          - int
          - test
          - acc
          
env: 
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'test' }}
  QA_LOGIN_EMAIL: ${{ secrets.QA_LOGIN_EMAIL }}
  QA_LOGIN_PASSWORD: ${{ secrets.QA_LOGIN_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19    

      - name: Test execution
        working-directory: ./qa
        run: | 
          if [[ "${{ inputs.TARGET_ENV }}" == 'int' ]]; then
            export TARGET_HOST="https://int-my.workstation.co.uk"
          elif [[ "${{ inputs.TARGET_ENV }}" == 'test' ]]; then
            export TARGET_HOST="https://test-my.workstation.co.uk"
          elif [[ "${{ inputs.TARGET_ENV }}" == 'acc' ]]; then
            export TARGET_HOST="https://acc-my.workstation.co.uk"
          elif [[ "${{ inputs.TARGET_ENV }}" == '' ]]; then
            export TARGET_HOST="https://test-my.workstation.co.uk"  
          else
            echo "Unsupported TARGET_ENV:${{ inputs.TARGET_ENV }}"
            exit 1
          fi  
          
          go mod init myapp
          go test -v 


  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules and Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-node${{ matrix.node-version }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }} --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=true,json=true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports

      - name: Publish JUnit Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: cypress/reports/*.xml

