name: Webimpetus Test Suite
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  

env: 
  QA_LOGIN_EMAIL: ${{ secrets.QA_LOGIN_EMAIL }}
  QA_LOGIN_PASSWORD: ${{ secrets.QA_LOGIN_PASSWORD }}
  TARGET_HOST: ${{ secrets.TARGET_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19    

    - name: Test Execution
      working-directory: ./qa
      run: | 
        go mod init myapp
        go test -v 

        
      
