name: Webimpetus Cypress UI tests suite by QA
on:
  # schedule:
  #   - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
          - int
          - test
          - acc
          
env: 
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'test' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose to run Cypress Test framework specs
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`
      - run: docker-compose --version

      - name: Getting Node to install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
            cd qa/cypress_ui_test
            ls -alt
            npm install
            ls -alt 
      
      - name: UI Test execution using Cypress on ${{ env.TARGET_ENV }}
        working-directory: ./qa/cypress_ui_test
        run: |
            ls -alt
            chmod +x ./qa-bootstrap-cypress.sh && sh ./qa-bootstrap-cypress.sh "${{ secrets.QA_LOGIN_EMAIL }}" "${{ secrets.QA_LOGIN_PASSWORD }}" "${{ env.TARGET_ENV }}"

      # - name: Slack Notification for Workstation CRM Cypress Test 
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #       SLACK_CHANNEL: general
      #       SLACK_COLOR: ${{ job.status }}
      #       SLACK_ICON: https://github.com/rtCamp.png?size=48
      #       SLACK_MESSAGE: 'Workstation CRM UI Test executed using Cypress Test framework ${{ env.TARGET_ENV }} env :rocket:'
      #       SLACK_TITLE: Workstation CRM Cypress UI Test on ${{ env.TARGET_ENV }}
      #       SLACK_USERNAME: rtCamp
      #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
