name: Webimpetus Cypress UI tests suite by QA
on:
  schedule:
    - cron: '0 21 * * *'
    
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
          - int
          - test
          - acc
          
env: 
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'test' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose to run Cypress Test framework specs
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`
      - run: docker-compose --version

      - name: Getting Node to install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd qa/cypress_ui_test 
      - run: npm i cypress-real-events -D     

      - name: UI Test execution using Cypress on ${{ env.TARGET_ENV }}
        working-directory: ./qa/cypress_ui_test
        run: |
            ls -alt
            chmod +x ./qa-bootstrap-cypress.sh && sh ./qa-bootstrap-cypress.sh "${{ secrets.QA_LOGIN_EMAIL }}" "${{ secrets.QA_LOGIN_PASSWORD }}" "${{ env.TARGET_ENV }}"

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
            token: ${{ secrets.SLACK_TOKEN_QA }}
            channels: 'cypress-test-results'
            workdir: qa/cypress_ui_test/cypress
            message-text: 'A QA Cypress UI test just finished for Workstation CRM . The screenshots and videos are available in this thread. Good luck!.'
   