name: Webimpetus UI tests

on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
        - int
        - test
        - acc
        - prod

env: 
  TARGET_ENV: ${{ inputs.TARGET_ENV }}
  QA_LOGIN_EMAIL: ${{ secrets.QA_LOGIN_EMAIL }}
  QA_LOGIN_PASSWORD: ${{ secrets.QA_LOGIN_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
        with:
          ref: dixa/qa-test
      
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Build docker image for selenium tests
        working-directory: ./qa
        run: docker build -t crm-selenium-tests -f Dockerfile_qa .

      - name: Test execution
        working-directory: ./qa
        run: |  
          if [[ "${{ inputs.TARGET_ENV }}" == 'int' ]]; then
            export TARGET_HOST="http://int2-my.workstation.co.uk"
          elif [[ "${{ inputs.TARGET_ENV }}" == 'test' ]]; then
            export TARGET_HOST="https://test-my.workstation.co.uk"
          elif [[ "${{ inputs.TARGET_ENV }}" == 'acc' ]]; then
            export TARGET_HOST="https://acc-my.workstation.co.uk"
          else
            echo "Unsupported TARGET_ENV:${{ inputs.TARGET_ENV }}"
            exit 1
          fi
          
          docker run -e QA_LOGIN_EMAIL=$QA_LOGIN_EMAIL -e QA_LOGIN_PASSWORD=$QA_LOGIN_PASSWORD -e TARGET_HOST=$TARGET_HOST crm-selenium-tests    

